<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Xiaoya Dong, Yingxue Wang, Yueqi He">
<meta name="dcterms.date" content="2025-04-21">

<title>AlphaSignal533 – alphasignal533</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ace74d340a4791061218a60df7c0f5e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>
<script src="https://cdn.plot.ly/plotly-2.12.1.min.js"></script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">alphasignal533</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/im-Tree/Fintech533-website"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#mean-reversion-strategy" id="toc-mean-reversion-strategy" class="nav-link active" data-scroll-target="#mean-reversion-strategy">Mean Reversion Strategy</a></li>
  <li><a href="#scoring-system" id="toc-scoring-system" class="nav-link" data-scroll-target="#scoring-system">Scoring System</a></li>
  <li><a href="#strategy-outcome" id="toc-strategy-outcome" class="nav-link" data-scroll-target="#strategy-outcome">Strategy Outcome</a></li>
  <li><a href="#limitations-and-future-enhancements" id="toc-limitations-and-future-enhancements" class="nav-link" data-scroll-target="#limitations-and-future-enhancements">Limitations and Future Enhancements</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">AlphaSignal533</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Xiaoya Dong, Yingxue Wang, Yueqi He </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 21, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="mean-reversion-strategy" class="level3">
<h3 class="anchored" data-anchor-id="mean-reversion-strategy">Mean Reversion Strategy</h3>
<section id="strategy-overview" class="level4">
<h4 class="anchored" data-anchor-id="strategy-overview">1. Strategy Overview</h4>
<p>This strategy is based on <strong>mean reversion</strong>, under the assumption that prices of large-cap, liquid stocks tend to revert to their average levels. When prices deviate significantly from the mean, they are expected to revert: - <strong>Go long</strong> when prices are abnormally low and expected to rebound. - <strong>Go short</strong> when prices are abnormally high and expected to pull back.</p>
<p>In addition, we are interested in studying how <strong>leverage control</strong> affects strategy performance. Without constraint, excessive leverage may amplify returns in the short term, but it can also lead to extreme losses and unstable drawdowns, especially when signals are weak or noisy. Therefore, we compare the performance of the strategy <strong>with and without leverage control</strong>.</p>
<hr>
</section>
<section id="portfolio-choice" class="level4">
<h4 class="anchored" data-anchor-id="portfolio-choice">2. Portfolio Choice</h4>
<p>We selected these 10 stocks for their strong <strong>sector representation</strong>, <strong>high liquidity</strong>, and <strong>market relevance</strong>. Each stock comes from a different major industry, ensuring diversification and reducing sector-specific risk.</p>
<div id="f6978ff6" class="cell" data-dataframe-index-label="No." data-dataframe-show-index="true" data-execution_count="1">
<div class="cell-output cell-output-display" data-execution_count="1">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Ticker</th>
<th data-quarto-table-cell-role="th">Industry</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1</td>
<td>AAPL</td>
<td>Information Electronics</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>MSFT</td>
<td>Information Technology</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3</td>
<td>JPM</td>
<td>Financial</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4</td>
<td>XOM</td>
<td>Energy</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5</td>
<td>JNJ</td>
<td>Healthcare</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">6</td>
<td>PG</td>
<td>Consumer Staples</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">7</td>
<td>NVDA</td>
<td>Semiconductors</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">8</td>
<td>CAT</td>
<td>Industrial</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">9</td>
<td>HD</td>
<td>Retail</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">10</td>
<td>AMZN</td>
<td>Communication Services</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<hr>
</section>
<section id="adjustment-method" class="level4">
<h4 class="anchored" data-anchor-id="adjustment-method">3. Adjustment Method</h4>
<ul>
<li><strong>Monthly portfolio adjustment</strong> based on re-ranking of stocks.</li>
<li><strong>Stop-loss and take-profit mechanism</strong>: Each stock position is monitored during the holding month and is closed early if either a stop-loss or take-profit threshold is reached. If no trigger is hit, the stock is force-closed at the end of the month.</li>
</ul>
<hr>
</section>
</section>
<section id="scoring-system" class="level3">
<h3 class="anchored" data-anchor-id="scoring-system">Scoring System</h3>
<section id="technical-indicator-scoring-system" class="level4">
<h4 class="anchored" data-anchor-id="technical-indicator-scoring-system">1. Technical Indicator Scoring System</h4>
<p>Each stock is scored for both long and short setups based on the following indicators:</p>
<section id="ema-deviation-delta-calculation" class="level5">
<h5 class="anchored" data-anchor-id="ema-deviation-delta-calculation">1.1 EMA Deviation (Delta) Calculation</h5>
<p>The <strong>EMA deviation</strong> measures how far the current price is from its 20-day Exponential Moving Average (EMA). It is calculated as: <code>Δ = 100% × (Close − EMA₍₂₀₎) / EMA₍₂₀₎</code></p>
<div id="8c9efbb3" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Δ Range</th>
<th data-quarto-table-cell-role="th">Short Score</th>
<th data-quarto-table-cell-role="th">Long Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1</td>
<td>&gt; +5%</td>
<td>5</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>+3% – +5%</td>
<td>4</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3</td>
<td>+1% – +3%</td>
<td>3</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4</td>
<td>0 – +1%</td>
<td>2</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5</td>
<td>&lt; 0%</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">6</td>
<td>&lt; –5%</td>
<td>0</td>
<td>5</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">7</td>
<td>–5% – –3%</td>
<td>0</td>
<td>4</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">8</td>
<td>–3% – –1%</td>
<td>0</td>
<td>3</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">9</td>
<td>–1% – 0%</td>
<td>0</td>
<td>2</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">10</td>
<td>&gt; 0%</td>
<td>0</td>
<td>0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="macd-moving-average-convergence-divergence" class="level5">
<h5 class="anchored" data-anchor-id="macd-moving-average-convergence-divergence">1.2 MACD (Moving Average Convergence Divergence)</h5>
<p>The <strong>MACD difference</strong> is calculated as: <code>MACD difference = MACD line – Signal line</code></p>
<div id="7a3a2cf8" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">MACD_diff Range</th>
<th data-quarto-table-cell-role="th">Short Score</th>
<th data-quarto-table-cell-role="th">Long Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1</td>
<td>&gt; +1.5</td>
<td>5</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>+1.0 – +1.5</td>
<td>4</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3</td>
<td>+0.5 – +1.0</td>
<td>3</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4</td>
<td>+0.1 – +0.5</td>
<td>2</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5</td>
<td>0 – +0.1</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">6</td>
<td>–0.1 – 0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">7</td>
<td>–0.5 – –0.1</td>
<td>0</td>
<td>2</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">8</td>
<td>–1.0 – –0.5</td>
<td>0</td>
<td>3</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">9</td>
<td>–1.5 – –1.0</td>
<td>0</td>
<td>4</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">10</td>
<td>&lt; –1.5</td>
<td>0</td>
<td>5</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="adx-average-directional-index" class="level5">
<h5 class="anchored" data-anchor-id="adx-average-directional-index">1.3 ADX (Average Directional Index)</h5>
<div id="536655b8" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ADX Value Range</th>
<th data-quarto-table-cell-role="th">Explanation</th>
<th data-quarto-table-cell-role="th">Score (Both Directions)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1</td>
<td>0–15</td>
<td>Very weak trend, sideways market</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>15–20</td>
<td>Weak trend, reversal possible</td>
<td>2</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3</td>
<td>20–30</td>
<td>Moderate trend, ideal for reversal</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4</td>
<td>30–40</td>
<td>Strong trend, caution</td>
<td>2</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5</td>
<td>&gt; 40</td>
<td>Very strong trend, high risk</td>
<td>0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="atr-average-true-range" class="level5">
<h5 class="anchored" data-anchor-id="atr-average-true-range">1.4 ATR (Average True Range)</h5>
<div id="99f8d204" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ATR Value Range</th>
<th data-quarto-table-cell-role="th">Explanation</th>
<th data-quarto-table-cell-role="th">Score (Both Directions)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1</td>
<td>&gt; 30</td>
<td>Extremely high volatility, avoid trading</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>20 – 30</td>
<td>High volatility, elevated risk</td>
<td>2</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3</td>
<td>10 – 20</td>
<td>Ideal volatility level</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4</td>
<td>5 – 10</td>
<td>Moderate-low volatility, acceptable</td>
<td>4</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5</td>
<td>&lt; 5</td>
<td>Very low volatility, may stall</td>
<td>2</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
</section>
<section id="non-technical-indicator-scoring-system" class="level4">
<h4 class="anchored" data-anchor-id="non-technical-indicator-scoring-system">2. Non-Technical Indicator Scoring System</h4>
<section id="implied-volatility" class="level5">
<h5 class="anchored" data-anchor-id="implied-volatility">2.1 Implied Volatility</h5>
<div id="78662b3a" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">IV Percentile Range</th>
<th data-quarto-table-cell-role="th">Long Score</th>
<th data-quarto-table-cell-role="th">Short Score</th>
<th data-quarto-table-cell-role="th">Explanation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1</td>
<td>&lt; 10%</td>
<td>5</td>
<td>0</td>
<td>Extremely calm, likely to rebound, long favorable</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>10% – 30%</td>
<td>4</td>
<td>1</td>
<td>Relatively calm, supports long</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3</td>
<td>30% – 70%</td>
<td>2</td>
<td>2</td>
<td>Neutral volatility, direction uncertain</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4</td>
<td>70% – 90%</td>
<td>1</td>
<td>4</td>
<td>Mild panic, possible short-term drop</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5</td>
<td>&gt; 90%</td>
<td>0</td>
<td>5</td>
<td>Extreme panic, suitable for shorting</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="yield-spread" class="level5">
<h5 class="anchored" data-anchor-id="yield-spread">2.2 10–2 Yield Spread</h5>
<div id="b4089e08" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">10–2 Spread Range (%)</th>
<th data-quarto-table-cell-role="th">Long Score</th>
<th data-quarto-table-cell-role="th">Short Score</th>
<th data-quarto-table-cell-role="th">Explanation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1</td>
<td>&gt; 1.5</td>
<td>5</td>
<td>0</td>
<td>Large spread, optimistic economy, strong rever...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>0.5 – 1.5</td>
<td>4</td>
<td>1</td>
<td>Mild steepness, supports long positions</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3</td>
<td>–0.5 – 0.5</td>
<td>2</td>
<td>2</td>
<td>Neutral curve, unclear direction</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4</td>
<td>–1.5 – –0.5</td>
<td>1</td>
<td>4</td>
<td>Significant inversion, growing concern</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5</td>
<td>&lt; –1.5</td>
<td>0</td>
<td>5</td>
<td>Severe inversion, market panic, short-favoring...</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<hr>
</section>
</section>
<section id="determining-trade-direction-weight-allocation" class="level4">
<h4 class="anchored" data-anchor-id="determining-trade-direction-weight-allocation">3. Determining Trade Direction &amp; Weight Allocation</h4>
<p>For each stock, we compute both long and short scores as weighted sums of indicator scores:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>Total_Long  <span class="op">=</span> <span class="fl">0.25</span> <span class="op">*</span> EMA_long <span class="op">+</span> <span class="fl">0.25</span> <span class="op">*</span> MACD_long <span class="op">+</span> <span class="fl">0.10</span> <span class="op">*</span> ADX <span class="op">+</span> <span class="fl">0.10</span> <span class="op">*</span> ATR <span class="op">+</span> <span class="fl">0.15</span> <span class="op">*</span> IV_long <span class="op">+</span> <span class="fl">0.15</span> <span class="op">*</span> Yield_long</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>Total_Short <span class="op">=</span> <span class="fl">0.25</span> <span class="op">*</span> EMA_short <span class="op">+</span> <span class="fl">0.25</span> <span class="op">*</span> MACD_short <span class="op">+</span> <span class="fl">0.10</span> <span class="op">*</span> ADX <span class="op">+</span> <span class="fl">0.10</span> <span class="op">*</span> ATR <span class="op">+</span> <span class="fl">0.15</span> <span class="op">*</span> IV_short <span class="op">+</span> <span class="fl">0.15</span> <span class="op">*</span> Yield_short</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The direction (LONG/SHORT) is determined based on which score is higher. The higher score is used to allocate capital.</p>
<section id="option-a-without-leverage-control" class="level5">
<h5 class="anchored" data-anchor-id="option-a-without-leverage-control">Option A: Without Leverage Control</h5>
<ul>
<li>All stocks are scored.</li>
<li>Normalize all non-zero scores to sum to 1:</li>
</ul>
<div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>weight_i <span class="op">=</span> score_i <span class="op">/</span> <span class="bu">sum</span>(<span class="op">|</span>scores<span class="op">|</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong>Pros</strong>: Simple.</li>
<li><strong>Cons</strong>: May lead to excessive total exposure, especially if all assets are scored as strong.</li>
</ul>
</section>
<section id="option-b-with-leverage-control" class="level5">
<h5 class="anchored" data-anchor-id="option-b-with-leverage-control">Option B: With Leverage Control</h5>
<ul>
<li>Split stocks into <strong>long group</strong> and <strong>short group</strong> based on score sign.</li>
<li>Normalize <strong>within group</strong>, then assign proportions:</li>
</ul>
<div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Assume MAX_GROSS_LEVERAGE = 1.5, max per stock = 0.2</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># long positions account for 60% of the total leverage</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>long_weights  <span class="op">=</span> score_i <span class="op">/</span> sum_long <span class="op">*</span> <span class="fl">0.6</span> <span class="op">*</span> MAX_GROSS_LEVERAGE</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># short positions account for 40% of the total leverage</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>short_weights <span class="op">=</span> score_i <span class="op">/</span> sum_short <span class="op">*</span> <span class="fl">0.4</span> <span class="op">*</span> MAX_GROSS_LEVERAGE</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li>Cap each stock to ±0.2 and re-normalize total exposure to 1.0</li>
<li><strong>Pros</strong>: Controlled leverage, avoids overweight.</li>
<li><strong>Cons</strong>: More complex.</li>
</ul>
<hr>
</section>
</section>
<section id="execution" class="level4">
<h4 class="anchored" data-anchor-id="execution">4. Execution</h4>
<ul>
<li>Entry is performed at the <strong>first hourly timestamp</strong> of the period.</li>
<li>Stop-loss and take-profit are set at dynamic thresholds derived from <strong>price volatility</strong>: entry_price*(1±vol_last_month).</li>
<li>If either threshold is hit intra-month, the position is closed early. Otherwise, all positions are force-closed at month end.</li>
</ul>
<hr>
<p>This strategy allows for clear comparison between raw signal-driven allocation and a risk-controlled variant, helping evaluate the cost and benefit of leverage in short-horizon mean reversion trading.</p>
</section>
</section>
<section id="strategy-outcome" class="level3">
<h3 class="anchored" data-anchor-id="strategy-outcome">Strategy Outcome</h3>
<p>The strategy produces a <strong>blotter</strong> and <strong>ledger</strong> to record all trade signals and executed positions based on the computed indicator scores.</p>
<p>Below is a placeholder for the interactive portfolio visualization. It will display results such as:</p>
<ul>
<li>Capital allocation weights (long/short)</li>
<li>Historical position tracking</li>
<li>Cumulative return curve</li>
</ul>
<section id="blotter" class="level4">
<h4 class="anchored" data-anchor-id="blotter"><strong>Blotter</strong></h4>
<section id="originalwithout-controlling-lever" class="level5">
<h5 class="anchored" data-anchor-id="originalwithout-controlling-lever"><strong>Original(without controlling lever)</strong></h5>
<p><input type="text" id="blotter-search" placeholder="Search by Period(e.g., 2025.01)" style="padding: 5px; margin-bottom: 10px; width: 300px;"></p>
<div style="max-height: 400px; overflow: auto; border: 1px solid #ccc; border-radius: 10px; padding: 10px;">
<div id="02b2215a" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<table id="blotter-table" class="dataframe table table-striped caption-top table-sm small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">trd_prd</th>
<th data-quarto-table-cell-role="th">AAPL weight</th>
<th data-quarto-table-cell-role="th">MSFT weight</th>
<th data-quarto-table-cell-role="th">JPM weight</th>
<th data-quarto-table-cell-role="th">XOM weight</th>
<th data-quarto-table-cell-role="th">JNJ weight</th>
<th data-quarto-table-cell-role="th">PG weight</th>
<th data-quarto-table-cell-role="th">NVDA weight</th>
<th data-quarto-table-cell-role="th">CAT weight</th>
<th data-quarto-table-cell-role="th">HD weight</th>
<th data-quarto-table-cell-role="th">AMZN weight</th>
<th data-quarto-table-cell-role="th">AAPL entry timestamp</th>
<th data-quarto-table-cell-role="th">MSFT entry timestamp</th>
<th data-quarto-table-cell-role="th">JPM entry timestamp</th>
<th data-quarto-table-cell-role="th">XOM entry timestamp</th>
<th data-quarto-table-cell-role="th">JNJ entry timestamp</th>
<th data-quarto-table-cell-role="th">PG entry timestamp</th>
<th data-quarto-table-cell-role="th">NVDA entry timestamp</th>
<th data-quarto-table-cell-role="th">CAT entry timestamp</th>
<th data-quarto-table-cell-role="th">HD entry timestamp</th>
<th data-quarto-table-cell-role="th">AMZN entry timestamp</th>
<th data-quarto-table-cell-role="th">AAPL exit timestamp</th>
<th data-quarto-table-cell-role="th">MSFT exit timestamp</th>
<th data-quarto-table-cell-role="th">JPM exit timestamp</th>
<th data-quarto-table-cell-role="th">XOM exit timestamp</th>
<th data-quarto-table-cell-role="th">JNJ exit timestamp</th>
<th data-quarto-table-cell-role="th">PG exit timestamp</th>
<th data-quarto-table-cell-role="th">NVDA exit timestamp</th>
<th data-quarto-table-cell-role="th">CAT exit timestamp</th>
<th data-quarto-table-cell-role="th">HD exit timestamp</th>
<th data-quarto-table-cell-role="th">AMZN exit timestamp</th>
<th data-quarto-table-cell-role="th">AAPL entry price</th>
<th data-quarto-table-cell-role="th">MSFT entry price</th>
<th data-quarto-table-cell-role="th">JPM entry price</th>
<th data-quarto-table-cell-role="th">XOM entry price</th>
<th data-quarto-table-cell-role="th">JNJ entry price</th>
<th data-quarto-table-cell-role="th">PG entry price</th>
<th data-quarto-table-cell-role="th">NVDA entry price</th>
<th data-quarto-table-cell-role="th">CAT entry price</th>
<th data-quarto-table-cell-role="th">HD entry price</th>
<th data-quarto-table-cell-role="th">AMZN entry price</th>
<th data-quarto-table-cell-role="th">AAPL exit price</th>
<th data-quarto-table-cell-role="th">MSFT exit price</th>
<th data-quarto-table-cell-role="th">JPM exit price</th>
<th data-quarto-table-cell-role="th">XOM exit price</th>
<th data-quarto-table-cell-role="th">JNJ exit price</th>
<th data-quarto-table-cell-role="th">PG exit price</th>
<th data-quarto-table-cell-role="th">NVDA exit price</th>
<th data-quarto-table-cell-role="th">CAT exit price</th>
<th data-quarto-table-cell-role="th">HD exit price</th>
<th data-quarto-table-cell-role="th">AMZN exit price</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2024.11</td>
<td>0.106719</td>
<td>0.124506</td>
<td>-0.088933</td>
<td>0.118577</td>
<td>0.098814</td>
<td>0.138340</td>
<td>0.098814</td>
<td>0.156126</td>
<td>0.144269</td>
<td>0.102767</td>
<td>2024-11-01 09:30:00</td>
<td>2024-11-01 09:30:00</td>
<td>2024-11-01 09:30:00</td>
<td>2024-11-01 09:30:00</td>
<td>2024-11-01 09:30:00</td>
<td>2024-11-01 09:30:00</td>
<td>2024-11-01 09:30:00</td>
<td>2024-11-01 09:30:00</td>
<td>2024-11-01 09:30:00</td>
<td>2024-11-01 09:30:00</td>
<td>2024-11-07 12:00:00</td>
<td>2024-11-07 09:30:00</td>
<td>2024-11-06 09:30:00</td>
<td>2024-11-01 12:00:00</td>
<td>2024-11-08 12:00:00</td>
<td>2024-11-06 11:00:00</td>
<td>2024-11-05 09:30:00</td>
<td>2024-11-06 09:30:00</td>
<td>2024-11-06 10:00:00</td>
<td>2024-11-06 11:00:00</td>
<td>221.00</td>
<td>409.00</td>
<td>223.56</td>
<td>119.65</td>
<td>160.58</td>
<td>165.31</td>
<td>134.70</td>
<td>378.07</td>
<td>394.80</td>
<td>198.88</td>
<td>227.20</td>
<td>421.90</td>
<td>240.47</td>
<td>116.29</td>
<td>156.11</td>
<td>160.32</td>
<td>138.77</td>
<td>409.22</td>
<td>382.40</td>
<td>205.57</td>
</tr>
<tr class="even">
<td>2024.12</td>
<td>-0.186246</td>
<td>-0.140401</td>
<td>-0.191977</td>
<td>0.143266</td>
<td>-0.106017</td>
<td>-0.200573</td>
<td>0.183381</td>
<td>-0.186246</td>
<td>-0.186246</td>
<td>-0.128940</td>
<td>2024-12-02 09:30:00</td>
<td>2024-12-02 09:30:00</td>
<td>2024-12-02 09:30:00</td>
<td>2024-12-02 09:30:00</td>
<td>2024-12-02 09:30:00</td>
<td>2024-12-02 09:30:00</td>
<td>2024-12-02 09:30:00</td>
<td>2024-12-02 09:30:00</td>
<td>2024-12-02 09:30:00</td>
<td>2024-12-02 09:30:00</td>
<td>2024-12-11 10:00:00</td>
<td>2024-12-05 12:00:00</td>
<td>2024-12-18 14:00:00</td>
<td>2024-12-11 10:00:00</td>
<td>2024-12-11 15:00:00</td>
<td>2024-12-18 09:30:00</td>
<td>2024-12-05 11:00:00</td>
<td>2024-12-12 09:30:00</td>
<td>2024-12-18 14:00:00</td>
<td>2024-12-05 12:00:00</td>
<td>237.27</td>
<td>421.57</td>
<td>249.55</td>
<td>118.05</td>
<td>154.75</td>
<td>179.12</td>
<td>138.83</td>
<td>407.46</td>
<td>429.00</td>
<td>209.90</td>
<td>250.14</td>
<td>443.94</td>
<td>234.00</td>
<td>111.69</td>
<td>146.64</td>
<td>169.56</td>
<td>146.08</td>
<td>385.24</td>
<td>397.82</td>
<td>221.54</td>
</tr>
<tr class="odd">
<td>2025.01</td>
<td>-0.126949</td>
<td>0.144766</td>
<td>0.113586</td>
<td>0.124722</td>
<td>0.091314</td>
<td>0.113586</td>
<td>0.142539</td>
<td>0.144766</td>
<td>0.131403</td>
<td>0.120267</td>
<td>2025-01-02 09:30:00</td>
<td>2025-01-02 09:30:00</td>
<td>2025-01-02 09:30:00</td>
<td>2025-01-02 09:30:00</td>
<td>2025-01-02 09:30:00</td>
<td>2025-01-02 09:30:00</td>
<td>2025-01-02 09:30:00</td>
<td>2025-01-02 09:30:00</td>
<td>2025-01-02 09:30:00</td>
<td>2025-01-02 09:30:00</td>
<td>2025-01-10 11:00:00</td>
<td>2025-01-31 00:00:00</td>
<td>2025-01-16 09:30:00</td>
<td>2025-01-31 00:00:00</td>
<td>2025-01-30 13:00:00</td>
<td>2025-01-10 14:00:00</td>
<td>2025-01-03 09:30:00</td>
<td>2025-01-17 11:00:00</td>
<td>2025-01-21 09:30:00</td>
<td>2025-01-22 11:00:00</td>
<td>248.93</td>
<td>425.53</td>
<td>240.92</td>
<td>108.28</td>
<td>145.23</td>
<td>168.10</td>
<td>136.00</td>
<td>365.51</td>
<td>392.13</td>
<td>222.44</td>
<td>234.89</td>
<td>415.06</td>
<td>256.01</td>
<td>106.83</td>
<td>154.01</td>
<td>157.79</td>
<td>143.93</td>
<td>386.36</td>
<td>416.46</td>
<td>235.07</td>
</tr>
<tr class="even">
<td>2025.02</td>
<td>0.239583</td>
<td>0.354167</td>
<td>-0.348958</td>
<td>-0.213542</td>
<td>-0.312500</td>
<td>-0.239583</td>
<td>0.385417</td>
<td>-0.244792</td>
<td>-0.286458</td>
<td>-0.333333</td>
<td>2025-02-03 09:30:00</td>
<td>2025-02-03 09:30:00</td>
<td>2025-02-03 09:30:00</td>
<td>2025-02-03 09:30:00</td>
<td>2025-02-03 09:30:00</td>
<td>2025-02-03 09:30:00</td>
<td>2025-02-03 09:30:00</td>
<td>2025-02-03 09:30:00</td>
<td>2025-02-03 09:30:00</td>
<td>2025-02-03 09:30:00</td>
<td>2025-02-21 11:00:00</td>
<td>2025-02-28 00:00:00</td>
<td>2025-02-28 00:00:00</td>
<td>2025-02-28 00:00:00</td>
<td>2025-02-21 14:00:00</td>
<td>2025-02-28 00:00:00</td>
<td>2025-02-05 11:00:00</td>
<td>2025-02-28 00:00:00</td>
<td>2025-02-28 00:00:00</td>
<td>2025-02-21 13:00:00</td>
<td>229.99</td>
<td>411.68</td>
<td>261.83</td>
<td>106.64</td>
<td>152.00</td>
<td>165.47</td>
<td>114.76</td>
<td>364.14</td>
<td>406.12</td>
<td>233.94</td>
<td>247.02</td>
<td>396.99</td>
<td>264.65</td>
<td>111.33</td>
<td>163.25</td>
<td>173.84</td>
<td>124.05</td>
<td>343.95</td>
<td>396.60</td>
<td>215.77</td>
</tr>
<tr class="odd">
<td>2025.03</td>
<td>-0.522936</td>
<td>0.532110</td>
<td>0.477064</td>
<td>-0.422018</td>
<td>-0.559633</td>
<td>-0.633028</td>
<td>0.550459</td>
<td>0.495413</td>
<td>0.541284</td>
<td>0.541284</td>
<td>2025-03-03 09:30:00</td>
<td>2025-03-03 09:30:00</td>
<td>2025-03-03 09:30:00</td>
<td>2025-03-03 09:30:00</td>
<td>2025-03-03 09:30:00</td>
<td>2025-03-03 09:30:00</td>
<td>2025-03-03 09:30:00</td>
<td>2025-03-03 09:30:00</td>
<td>2025-03-03 09:30:00</td>
<td>2025-03-03 09:30:00</td>
<td>2025-03-12 10:00:00</td>
<td>2025-03-31 00:00:00</td>
<td>2025-03-10 09:30:00</td>
<td>2025-03-31 00:00:00</td>
<td>2025-03-31 00:00:00</td>
<td>2025-03-31 00:00:00</td>
<td>2025-03-06 14:00:00</td>
<td>2025-03-31 00:00:00</td>
<td>2025-03-13 09:30:00</td>
<td>2025-03-10 10:00:00</td>
<td>241.81</td>
<td>398.82</td>
<td>264.00</td>
<td>111.70</td>
<td>164.96</td>
<td>173.58</td>
<td>123.50</td>
<td>347.63</td>
<td>396.95</td>
<td>213.17</td>
<td>216.10</td>
<td>375.39</td>
<td>234.95</td>
<td>118.93</td>
<td>165.84</td>
<td>170.42</td>
<td>110.84</td>
<td>329.80</td>
<td>354.79</td>
<td>191.09</td>
</tr>
<tr class="even">
<td>2025.04</td>
<td>0.228311</td>
<td>0.214612</td>
<td>-0.136986</td>
<td>-0.305936</td>
<td>0.182648</td>
<td>0.210046</td>
<td>0.301370</td>
<td>-0.200913</td>
<td>0.178082</td>
<td>0.328767</td>
<td>2025-04-01 09:30:00</td>
<td>2025-04-01 09:30:00</td>
<td>2025-04-01 09:30:00</td>
<td>2025-04-01 09:30:00</td>
<td>2025-04-01 09:30:00</td>
<td>2025-04-01 09:30:00</td>
<td>2025-04-01 09:30:00</td>
<td>2025-04-01 09:30:00</td>
<td>2025-04-01 09:30:00</td>
<td>2025-04-01 09:30:00</td>
<td>2025-04-03 09:30:00</td>
<td>2025-04-07 09:30:00</td>
<td>2025-04-03 10:00:00</td>
<td>2025-04-03 14:00:00</td>
<td>2025-04-07 09:30:00</td>
<td>2025-04-07 09:30:00</td>
<td>2025-04-03 10:00:00</td>
<td>2025-04-03 10:00:00</td>
<td>2025-04-07 09:30:00</td>
<td>2025-04-02 12:00:00</td>
<td>219.87</td>
<td>374.65</td>
<td>242.62</td>
<td>119.22</td>
<td>160.73</td>
<td>170.57</td>
<td>108.52</td>
<td>327.01</td>
<td>364.14</td>
<td>187.86</td>
<td>204.36</td>
<td>353.35</td>
<td>227.65</td>
<td>113.16</td>
<td>148.41</td>
<td>160.57</td>
<td>102.78</td>
<td>309.20</td>
<td>339.60</td>
<td>197.12</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<script>
document.addEventListener("DOMContentLoaded", function () {
  const input = document.getElementById("blotter-search");
  input.addEventListener("keyup", function () {
    const filter = input.value.toLowerCase();
    const rows = document.querySelectorAll("#blotter-table tbody tr");
    rows.forEach(row => {
      const dateCell = row.cells[0]?.textContent?.toLowerCase() || "";
      if (dateCell.includes(filter)) {
        row.style.display = "";
      } else {
        row.style.display = "none";
      }
    });
  });
});
</script>
</section>
<section id="after-controlling-lever" class="level5">
<h5 class="anchored" data-anchor-id="after-controlling-lever"><strong>After Controlling Lever</strong></h5>
<p><input type="text" id="blotter-search" placeholder="Search by Period(e.g., 2025.01)" style="padding: 5px; margin-bottom: 10px; width: 300px;"></p>
<div style="max-height: 400px; overflow: auto; border: 1px solid #ccc; border-radius: 10px; padding: 10px;">
<div id="a4ab1e7d" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display">
<table id="blotter-table" class="dataframe table table-striped caption-top table-sm small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">trd_prd</th>
<th data-quarto-table-cell-role="th">AAPL weight</th>
<th data-quarto-table-cell-role="th">MSFT weight</th>
<th data-quarto-table-cell-role="th">JPM weight</th>
<th data-quarto-table-cell-role="th">XOM weight</th>
<th data-quarto-table-cell-role="th">JNJ weight</th>
<th data-quarto-table-cell-role="th">PG weight</th>
<th data-quarto-table-cell-role="th">NVDA weight</th>
<th data-quarto-table-cell-role="th">CAT weight</th>
<th data-quarto-table-cell-role="th">HD weight</th>
<th data-quarto-table-cell-role="th">AMZN weight</th>
<th data-quarto-table-cell-role="th">AAPL entry timestamp</th>
<th data-quarto-table-cell-role="th">MSFT entry timestamp</th>
<th data-quarto-table-cell-role="th">JPM entry timestamp</th>
<th data-quarto-table-cell-role="th">XOM entry timestamp</th>
<th data-quarto-table-cell-role="th">JNJ entry timestamp</th>
<th data-quarto-table-cell-role="th">PG entry timestamp</th>
<th data-quarto-table-cell-role="th">NVDA entry timestamp</th>
<th data-quarto-table-cell-role="th">CAT entry timestamp</th>
<th data-quarto-table-cell-role="th">HD entry timestamp</th>
<th data-quarto-table-cell-role="th">AMZN entry timestamp</th>
<th data-quarto-table-cell-role="th">AAPL exit timestamp</th>
<th data-quarto-table-cell-role="th">MSFT exit timestamp</th>
<th data-quarto-table-cell-role="th">JPM exit timestamp</th>
<th data-quarto-table-cell-role="th">XOM exit timestamp</th>
<th data-quarto-table-cell-role="th">JNJ exit timestamp</th>
<th data-quarto-table-cell-role="th">PG exit timestamp</th>
<th data-quarto-table-cell-role="th">NVDA exit timestamp</th>
<th data-quarto-table-cell-role="th">CAT exit timestamp</th>
<th data-quarto-table-cell-role="th">HD exit timestamp</th>
<th data-quarto-table-cell-role="th">AMZN exit timestamp</th>
<th data-quarto-table-cell-role="th">AAPL entry price</th>
<th data-quarto-table-cell-role="th">MSFT entry price</th>
<th data-quarto-table-cell-role="th">JPM entry price</th>
<th data-quarto-table-cell-role="th">XOM entry price</th>
<th data-quarto-table-cell-role="th">JNJ entry price</th>
<th data-quarto-table-cell-role="th">PG entry price</th>
<th data-quarto-table-cell-role="th">NVDA entry price</th>
<th data-quarto-table-cell-role="th">CAT entry price</th>
<th data-quarto-table-cell-role="th">HD entry price</th>
<th data-quarto-table-cell-role="th">AMZN entry price</th>
<th data-quarto-table-cell-role="th">AAPL exit price</th>
<th data-quarto-table-cell-role="th">MSFT exit price</th>
<th data-quarto-table-cell-role="th">JPM exit price</th>
<th data-quarto-table-cell-role="th">XOM exit price</th>
<th data-quarto-table-cell-role="th">JNJ exit price</th>
<th data-quarto-table-cell-role="th">PG exit price</th>
<th data-quarto-table-cell-role="th">NVDA exit price</th>
<th data-quarto-table-cell-role="th">CAT exit price</th>
<th data-quarto-table-cell-role="th">HD exit price</th>
<th data-quarto-table-cell-role="th">AMZN exit price</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2024.11</td>
<td>0.080185</td>
<td>0.093549</td>
<td>-0.181818</td>
<td>0.089094</td>
<td>0.074245</td>
<td>0.103943</td>
<td>0.074245</td>
<td>0.117307</td>
<td>0.108398</td>
<td>0.077215</td>
<td>2024-11-01 09:30:00</td>
<td>2024-11-01 09:30:00</td>
<td>2024-11-01 09:30:00</td>
<td>2024-11-01 09:30:00</td>
<td>2024-11-01 09:30:00</td>
<td>2024-11-01 09:30:00</td>
<td>2024-11-01 09:30:00</td>
<td>2024-11-01 09:30:00</td>
<td>2024-11-01 09:30:00</td>
<td>2024-11-01 09:30:00</td>
<td>2024-11-07 12:00:00</td>
<td>2024-11-07 09:30:00</td>
<td>2024-11-06 09:30:00</td>
<td>2024-11-01 12:00:00</td>
<td>2024-11-08 12:00:00</td>
<td>2024-11-06 11:00:00</td>
<td>2024-11-05 09:30:00</td>
<td>2024-11-06 09:30:00</td>
<td>2024-11-06 10:00:00</td>
<td>2024-11-06 11:00:00</td>
<td>221.00</td>
<td>409.00</td>
<td>223.56</td>
<td>119.65</td>
<td>160.58</td>
<td>165.31</td>
<td>134.70</td>
<td>378.07</td>
<td>394.80</td>
<td>198.88</td>
<td>227.20</td>
<td>421.90</td>
<td>240.47</td>
<td>116.29</td>
<td>156.11</td>
<td>160.32</td>
<td>138.77</td>
<td>409.22</td>
<td>382.40</td>
<td>205.57</td>
</tr>
<tr class="even">
<td>2024.12</td>
<td>-0.084233</td>
<td>-0.063499</td>
<td>-0.086825</td>
<td>0.200000</td>
<td>-0.047948</td>
<td>-0.090713</td>
<td>0.200000</td>
<td>-0.084233</td>
<td>-0.084233</td>
<td>-0.058315</td>
<td>2024-12-02 09:30:00</td>
<td>2024-12-02 09:30:00</td>
<td>2024-12-02 09:30:00</td>
<td>2024-12-02 09:30:00</td>
<td>2024-12-02 09:30:00</td>
<td>2024-12-02 09:30:00</td>
<td>2024-12-02 09:30:00</td>
<td>2024-12-02 09:30:00</td>
<td>2024-12-02 09:30:00</td>
<td>2024-12-02 09:30:00</td>
<td>2024-12-11 10:00:00</td>
<td>2024-12-05 12:00:00</td>
<td>2024-12-18 14:00:00</td>
<td>2024-12-11 10:00:00</td>
<td>2024-12-11 15:00:00</td>
<td>2024-12-18 09:30:00</td>
<td>2024-12-05 11:00:00</td>
<td>2024-12-12 09:30:00</td>
<td>2024-12-18 14:00:00</td>
<td>2024-12-05 12:00:00</td>
<td>237.27</td>
<td>421.57</td>
<td>249.55</td>
<td>118.05</td>
<td>154.75</td>
<td>179.12</td>
<td>138.83</td>
<td>407.46</td>
<td>429.00</td>
<td>209.90</td>
<td>250.14</td>
<td>443.94</td>
<td>234.00</td>
<td>111.69</td>
<td>146.64</td>
<td>169.56</td>
<td>146.08</td>
<td>385.24</td>
<td>397.82</td>
<td>221.54</td>
</tr>
<tr class="odd">
<td>2025.01</td>
<td>-0.181818</td>
<td>0.105102</td>
<td>0.082465</td>
<td>0.090550</td>
<td>0.066295</td>
<td>0.082465</td>
<td>0.103485</td>
<td>0.105102</td>
<td>0.095401</td>
<td>0.087316</td>
<td>2025-01-02 09:30:00</td>
<td>2025-01-02 09:30:00</td>
<td>2025-01-02 09:30:00</td>
<td>2025-01-02 09:30:00</td>
<td>2025-01-02 09:30:00</td>
<td>2025-01-02 09:30:00</td>
<td>2025-01-02 09:30:00</td>
<td>2025-01-02 09:30:00</td>
<td>2025-01-02 09:30:00</td>
<td>2025-01-02 09:30:00</td>
<td>2025-01-10 11:00:00</td>
<td>2025-01-31 00:00:00</td>
<td>2025-01-16 09:30:00</td>
<td>2025-01-31 00:00:00</td>
<td>2025-01-30 13:00:00</td>
<td>2025-01-10 14:00:00</td>
<td>2025-01-03 09:30:00</td>
<td>2025-01-17 11:00:00</td>
<td>2025-01-21 09:30:00</td>
<td>2025-01-22 11:00:00</td>
<td>248.93</td>
<td>425.53</td>
<td>240.92</td>
<td>108.28</td>
<td>145.23</td>
<td>168.10</td>
<td>136.00</td>
<td>365.51</td>
<td>392.13</td>
<td>222.44</td>
<td>234.89</td>
<td>415.06</td>
<td>256.01</td>
<td>106.83</td>
<td>154.01</td>
<td>157.79</td>
<td>143.93</td>
<td>386.36</td>
<td>416.46</td>
<td>235.07</td>
</tr>
<tr class="even">
<td>2025.02</td>
<td>0.166667</td>
<td>0.166667</td>
<td>-0.088158</td>
<td>-0.053947</td>
<td>-0.078947</td>
<td>-0.060526</td>
<td>0.166667</td>
<td>-0.061842</td>
<td>-0.072368</td>
<td>-0.084211</td>
<td>2025-02-03 09:30:00</td>
<td>2025-02-03 09:30:00</td>
<td>2025-02-03 09:30:00</td>
<td>2025-02-03 09:30:00</td>
<td>2025-02-03 09:30:00</td>
<td>2025-02-03 09:30:00</td>
<td>2025-02-03 09:30:00</td>
<td>2025-02-03 09:30:00</td>
<td>2025-02-03 09:30:00</td>
<td>2025-02-03 09:30:00</td>
<td>2025-02-21 11:00:00</td>
<td>2025-02-28 00:00:00</td>
<td>2025-02-28 00:00:00</td>
<td>2025-02-28 00:00:00</td>
<td>2025-02-21 14:00:00</td>
<td>2025-02-28 00:00:00</td>
<td>2025-02-05 11:00:00</td>
<td>2025-02-28 00:00:00</td>
<td>2025-02-28 00:00:00</td>
<td>2025-02-21 13:00:00</td>
<td>229.99</td>
<td>411.68</td>
<td>261.83</td>
<td>106.64</td>
<td>152.00</td>
<td>165.47</td>
<td>114.76</td>
<td>364.14</td>
<td>406.12</td>
<td>233.94</td>
<td>247.02</td>
<td>396.99</td>
<td>264.65</td>
<td>111.33</td>
<td>163.25</td>
<td>173.84</td>
<td>124.05</td>
<td>343.95</td>
<td>396.60</td>
<td>215.77</td>
</tr>
<tr class="odd">
<td>2025.03</td>
<td>-0.097854</td>
<td>0.101754</td>
<td>0.091228</td>
<td>-0.078970</td>
<td>-0.104721</td>
<td>-0.118455</td>
<td>0.105263</td>
<td>0.094737</td>
<td>0.103509</td>
<td>0.103509</td>
<td>2025-03-03 09:30:00</td>
<td>2025-03-03 09:30:00</td>
<td>2025-03-03 09:30:00</td>
<td>2025-03-03 09:30:00</td>
<td>2025-03-03 09:30:00</td>
<td>2025-03-03 09:30:00</td>
<td>2025-03-03 09:30:00</td>
<td>2025-03-03 09:30:00</td>
<td>2025-03-03 09:30:00</td>
<td>2025-03-03 09:30:00</td>
<td>2025-03-12 10:00:00</td>
<td>2025-03-31 00:00:00</td>
<td>2025-03-10 09:30:00</td>
<td>2025-03-31 00:00:00</td>
<td>2025-03-31 00:00:00</td>
<td>2025-03-31 00:00:00</td>
<td>2025-03-06 14:00:00</td>
<td>2025-03-31 00:00:00</td>
<td>2025-03-13 09:30:00</td>
<td>2025-03-10 10:00:00</td>
<td>241.81</td>
<td>398.82</td>
<td>264.00</td>
<td>111.70</td>
<td>164.96</td>
<td>173.58</td>
<td>123.50</td>
<td>347.63</td>
<td>396.95</td>
<td>213.17</td>
<td>216.10</td>
<td>375.39</td>
<td>234.95</td>
<td>118.93</td>
<td>165.84</td>
<td>170.42</td>
<td>110.84</td>
<td>329.80</td>
<td>354.79</td>
<td>191.09</td>
</tr>
<tr class="even">
<td>2025.04</td>
<td>0.088346</td>
<td>0.083045</td>
<td>-0.090226</td>
<td>-0.141353</td>
<td>0.070677</td>
<td>0.081278</td>
<td>0.116617</td>
<td>-0.132331</td>
<td>0.068910</td>
<td>0.127218</td>
<td>2025-04-01 09:30:00</td>
<td>2025-04-01 09:30:00</td>
<td>2025-04-01 09:30:00</td>
<td>2025-04-01 09:30:00</td>
<td>2025-04-01 09:30:00</td>
<td>2025-04-01 09:30:00</td>
<td>2025-04-01 09:30:00</td>
<td>2025-04-01 09:30:00</td>
<td>2025-04-01 09:30:00</td>
<td>2025-04-01 09:30:00</td>
<td>2025-04-03 09:30:00</td>
<td>2025-04-07 09:30:00</td>
<td>2025-04-03 10:00:00</td>
<td>2025-04-03 14:00:00</td>
<td>2025-04-07 09:30:00</td>
<td>2025-04-07 09:30:00</td>
<td>2025-04-03 10:00:00</td>
<td>2025-04-03 10:00:00</td>
<td>2025-04-07 09:30:00</td>
<td>2025-04-02 12:00:00</td>
<td>219.87</td>
<td>374.65</td>
<td>242.62</td>
<td>119.22</td>
<td>160.73</td>
<td>170.57</td>
<td>108.52</td>
<td>327.01</td>
<td>364.14</td>
<td>187.86</td>
<td>204.36</td>
<td>353.35</td>
<td>227.65</td>
<td>113.16</td>
<td>148.41</td>
<td>160.57</td>
<td>102.78</td>
<td>309.20</td>
<td>339.60</td>
<td>197.12</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<script>
document.addEventListener("DOMContentLoaded", function () {
  const input = document.getElementById("blotter-search");
  input.addEventListener("keyup", function () {
    const filter = input.value.toLowerCase();
    const rows = document.querySelectorAll("#blotter-table tbody tr");
    rows.forEach(row => {
      const dateCell = row.cells[0]?.textContent?.toLowerCase() || "";
      if (dateCell.includes(filter)) {
        row.style.display = "";
      } else {
        row.style.display = "none";
      }
    });
  });
});
</script>
</section>
</section>
<section id="ledger" class="level4">
<h4 class="anchored" data-anchor-id="ledger"><strong>Ledger</strong></h4>
<section id="originalwithout-controlling-lever-1" class="level5">
<h5 class="anchored" data-anchor-id="originalwithout-controlling-lever-1"><strong>Original(without controlling lever)</strong></h5>
<p><input type="text" id="ledger-search" placeholder="Search by Date(e.g., 2025-04-15)" style="padding: 5px; margin-bottom: 10px; width: 300px;"></p>
<div style="max-height: 400px; overflow: auto; border: 1px solid #ccc; border-radius: 10px; padding: 10px;">
<div id="d7659ec9" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<table id="ledger-table" class="dataframe table table-striped caption-top table-sm small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Date</th>
<th data-quarto-table-cell-role="th">Cash</th>
<th data-quarto-table-cell-role="th">AAPL Qty</th>
<th data-quarto-table-cell-role="th">MSFT Qty</th>
<th data-quarto-table-cell-role="th">JPM Qty</th>
<th data-quarto-table-cell-role="th">XOM Qty</th>
<th data-quarto-table-cell-role="th">JNJ Qty</th>
<th data-quarto-table-cell-role="th">PG Qty</th>
<th data-quarto-table-cell-role="th">NVDA Qty</th>
<th data-quarto-table-cell-role="th">CAT Qty</th>
<th data-quarto-table-cell-role="th">HD Qty</th>
<th data-quarto-table-cell-role="th">AMZN Qty</th>
<th data-quarto-table-cell-role="th">AAPL Close</th>
<th data-quarto-table-cell-role="th">MSFT Close</th>
<th data-quarto-table-cell-role="th">JPM Close</th>
<th data-quarto-table-cell-role="th">XOM Close</th>
<th data-quarto-table-cell-role="th">JNJ Close</th>
<th data-quarto-table-cell-role="th">PG Close</th>
<th data-quarto-table-cell-role="th">NVDA Close</th>
<th data-quarto-table-cell-role="th">CAT Close</th>
<th data-quarto-table-cell-role="th">HD Close</th>
<th data-quarto-table-cell-role="th">AMZN Close</th>
<th data-quarto-table-cell-role="th">Portfolio Value</th>
<th data-quarto-table-cell-role="th">Market Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2024-11-01</td>
<td>116385.68</td>
<td>482</td>
<td>304</td>
<td>-397</td>
<td>0</td>
<td>615</td>
<td>836</td>
<td>733</td>
<td>412</td>
<td>365</td>
<td>516</td>
<td>222.91</td>
<td>410.37</td>
<td>222.94</td>
<td>114.95</td>
<td>160.13</td>
<td>165.10</td>
<td>135.40</td>
<td>379.63</td>
<td>392.59</td>
<td>197.93</td>
<td>881274.46</td>
<td>997660.14</td>
</tr>
<tr class="even">
<td>2024-11-04</td>
<td>116385.68</td>
<td>482</td>
<td>304</td>
<td>-397</td>
<td>0</td>
<td>615</td>
<td>836</td>
<td>733</td>
<td>412</td>
<td>365</td>
<td>516</td>
<td>222.01</td>
<td>408.46</td>
<td>219.78</td>
<td>118.61</td>
<td>158.24</td>
<td>165.08</td>
<td>136.05</td>
<td>376.52</td>
<td>395.57</td>
<td>195.78</td>
<td>879508.90</td>
<td>995894.58</td>
</tr>
<tr class="odd">
<td>2024-11-05</td>
<td>218104.09</td>
<td>482</td>
<td>304</td>
<td>-397</td>
<td>0</td>
<td>615</td>
<td>836</td>
<td>0</td>
<td>412</td>
<td>365</td>
<td>516</td>
<td>223.45</td>
<td>411.46</td>
<td>221.49</td>
<td>118.96</td>
<td>158.35</td>
<td>165.76</td>
<td>139.91</td>
<td>383.37</td>
<td>400.09</td>
<td>199.50</td>
<td>787739.11</td>
<td>1005843.20</td>
</tr>
<tr class="even">
<td>2024-11-06</td>
<td>670913.78</td>
<td>482</td>
<td>304</td>
<td>0</td>
<td>0</td>
<td>615</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>222.72</td>
<td>420.18</td>
<td>247.06</td>
<td>121.00</td>
<td>157.88</td>
<td>161.05</td>
<td>145.61</td>
<td>416.88</td>
<td>388.37</td>
<td>207.09</td>
<td>332181.96</td>
<td>1003095.74</td>
</tr>
<tr class="odd">
<td>2024-11-07</td>
<td>908681.78</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>615</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>227.48</td>
<td>425.43</td>
<td>236.38</td>
<td>121.15</td>
<td>156.73</td>
<td>163.41</td>
<td>148.88</td>
<td>408.21</td>
<td>399.44</td>
<td>210.05</td>
<td>96388.95</td>
<td>1005070.73</td>
</tr>
<tr class="even">
<td>2024-11-08</td>
<td>1004689.43</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>226.96</td>
<td>422.54</td>
<td>236.98</td>
<td>121.11</td>
<td>155.47</td>
<td>167.71</td>
<td>147.63</td>
<td>393.37</td>
<td>405.90</td>
<td>208.18</td>
<td>0.00</td>
<td>1004689.43</td>
</tr>
<tr class="odd">
<td>2024-11-11</td>
<td>1004689.43</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>224.23</td>
<td>418.01</td>
<td>239.29</td>
<td>120.47</td>
<td>155.04</td>
<td>166.03</td>
<td>145.26</td>
<td>396.54</td>
<td>408.29</td>
<td>206.84</td>
<td>0.00</td>
<td>1004689.43</td>
</tr>
<tr class="even">
<td>2024-11-12</td>
<td>1004689.43</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>224.23</td>
<td>423.03</td>
<td>239.56</td>
<td>120.35</td>
<td>152.64</td>
<td>165.84</td>
<td>148.29</td>
<td>393.01</td>
<td>403.08</td>
<td>208.91</td>
<td>0.00</td>
<td>1004689.43</td>
</tr>
<tr class="odd">
<td>2024-11-13</td>
<td>1004689.43</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>225.12</td>
<td>425.20</td>
<td>241.16</td>
<td>121.47</td>
<td>153.24</td>
<td>166.58</td>
<td>146.27</td>
<td>387.07</td>
<td>410.19</td>
<td>214.10</td>
<td>0.00</td>
<td>1004689.43</td>
</tr>
<tr class="even">
<td>2024-11-14</td>
<td>1004689.43</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>228.22</td>
<td>426.89</td>
<td>241.87</td>
<td>120.56</td>
<td>151.87</td>
<td>167.08</td>
<td>146.76</td>
<td>387.36</td>
<td>405.72</td>
<td>211.48</td>
<td>0.00</td>
<td>1004689.43</td>
</tr>
<tr class="odd">
<td>2024-11-15</td>
<td>1004689.43</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>225.00</td>
<td>415.00</td>
<td>245.31</td>
<td>119.31</td>
<td>154.00</td>
<td>169.54</td>
<td>141.98</td>
<td>384.07</td>
<td>408.18</td>
<td>202.61</td>
<td>0.00</td>
<td>1004689.43</td>
</tr>
<tr class="even">
<td>2024-11-18</td>
<td>1004689.43</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>228.02</td>
<td>415.76</td>
<td>245.03</td>
<td>120.31</td>
<td>154.77</td>
<td>170.75</td>
<td>140.15</td>
<td>384.46</td>
<td>410.44</td>
<td>201.70</td>
<td>0.00</td>
<td>1004689.43</td>
</tr>
<tr class="odd">
<td>2024-11-19</td>
<td>1004689.43</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>228.28</td>
<td>417.79</td>
<td>243.09</td>
<td>118.63</td>
<td>153.00</td>
<td>170.76</td>
<td>147.01</td>
<td>382.33</td>
<td>406.80</td>
<td>204.61</td>
<td>0.00</td>
<td>1004689.43</td>
</tr>
<tr class="even">
<td>2024-11-20</td>
<td>1004689.43</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>229.00</td>
<td>415.49</td>
<td>240.78</td>
<td>120.32</td>
<td>153.11</td>
<td>170.89</td>
<td>145.89</td>
<td>381.50</td>
<td>400.00</td>
<td>202.88</td>
<td>0.00</td>
<td>1004689.43</td>
</tr>
<tr class="odd">
<td>2024-11-21</td>
<td>1004689.43</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>228.52</td>
<td>412.87</td>
<td>244.76</td>
<td>121.93</td>
<td>155.50</td>
<td>172.75</td>
<td>146.67</td>
<td>389.59</td>
<td>410.45</td>
<td>198.38</td>
<td>0.00</td>
<td>1004689.43</td>
</tr>
<tr class="even">
<td>2024-11-22</td>
<td>1004689.43</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>229.87</td>
<td>417.00</td>
<td>248.55</td>
<td>121.79</td>
<td>155.17</td>
<td>176.28</td>
<td>141.95</td>
<td>397.49</td>
<td>420.00</td>
<td>197.12</td>
<td>0.00</td>
<td>1004689.43</td>
</tr>
<tr class="odd">
<td>2024-11-25</td>
<td>1004689.43</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>232.87</td>
<td>418.79</td>
<td>250.29</td>
<td>119.97</td>
<td>155.78</td>
<td>177.39</td>
<td>136.02</td>
<td>405.65</td>
<td>428.67</td>
<td>201.45</td>
<td>0.00</td>
<td>1004689.43</td>
</tr>
<tr class="even">
<td>2024-11-26</td>
<td>1004689.43</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>235.06</td>
<td>427.99</td>
<td>249.97</td>
<td>117.97</td>
<td>154.52</td>
<td>179.31</td>
<td>136.92</td>
<td>407.83</td>
<td>429.52</td>
<td>207.86</td>
<td>0.00</td>
<td>1004689.43</td>
</tr>
<tr class="odd">
<td>2024-11-27</td>
<td>1004689.43</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>234.93</td>
<td>422.99</td>
<td>249.79</td>
<td>117.66</td>
<td>155.40</td>
<td>179.36</td>
<td>135.34</td>
<td>403.70</td>
<td>427.19</td>
<td>205.74</td>
<td>0.00</td>
<td>1004689.43</td>
</tr>
<tr class="even">
<td>2024-11-29</td>
<td>1004689.43</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>237.33</td>
<td>423.46</td>
<td>249.72</td>
<td>117.96</td>
<td>155.01</td>
<td>179.26</td>
<td>138.25</td>
<td>406.11</td>
<td>429.13</td>
<td>207.89</td>
<td>0.00</td>
<td>1004689.43</td>
</tr>
<tr class="odd">
<td>2024-12-02</td>
<td>2004258.47</td>
<td>-784</td>
<td>-333</td>
<td>-769</td>
<td>1213</td>
<td>-685</td>
<td>-1119</td>
<td>1320</td>
<td>-457</td>
<td>-434</td>
<td>-614</td>
<td>239.59</td>
<td>430.98</td>
<td>246.25</td>
<td>117.85</td>
<td>154.80</td>
<td>179.70</td>
<td>138.63</td>
<td>402.51</td>
<td>426.96</td>
<td>210.71</td>
<td>-1000523.45</td>
<td>1003735.02</td>
</tr>
<tr class="even">
<td>2024-12-03</td>
<td>2004258.47</td>
<td>-784</td>
<td>-333</td>
<td>-769</td>
<td>1213</td>
<td>-685</td>
<td>-1119</td>
<td>1320</td>
<td>-457</td>
<td>-434</td>
<td>-614</td>
<td>242.65</td>
<td>431.20</td>
<td>244.82</td>
<td>117.67</td>
<td>152.36</td>
<td>175.42</td>
<td>140.26</td>
<td>399.26</td>
<td>429.35</td>
<td>213.44</td>
<td>-994730.33</td>
<td>1009528.14</td>
</tr>
<tr class="odd">
<td>2024-12-04</td>
<td>2004258.47</td>
<td>-784</td>
<td>-333</td>
<td>-769</td>
<td>1213</td>
<td>-685</td>
<td>-1119</td>
<td>1320</td>
<td>-457</td>
<td>-434</td>
<td>-614</td>
<td>243.01</td>
<td>437.42</td>
<td>243.40</td>
<td>114.28</td>
<td>150.47</td>
<td>175.11</td>
<td>145.14</td>
<td>399.51</td>
<td>427.92</td>
<td>218.16</td>
<td>-994412.49</td>
<td>1009845.98</td>
</tr>
<tr class="even">
<td>2024-12-05</td>
<td>1913226.49</td>
<td>-784</td>
<td>0</td>
<td>-769</td>
<td>1213</td>
<td>-685</td>
<td>-1119</td>
<td>0</td>
<td>-457</td>
<td>-434</td>
<td>0</td>
<td>243.04</td>
<td>442.62</td>
<td>245.48</td>
<td>114.78</td>
<td>149.52</td>
<td>176.03</td>
<td>145.06</td>
<td>394.98</td>
<td>426.54</td>
<td>220.55</td>
<td>-905112.33</td>
<td>1008114.16</td>
</tr>
<tr class="odd">
<td>2024-12-06</td>
<td>1913226.49</td>
<td>-784</td>
<td>0</td>
<td>-769</td>
<td>1213</td>
<td>-685</td>
<td>-1119</td>
<td>0</td>
<td>-457</td>
<td>-434</td>
<td>0</td>
<td>242.84</td>
<td>443.57</td>
<td>247.36</td>
<td>113.57</td>
<td>149.31</td>
<td>173.82</td>
<td>142.44</td>
<td>395.03</td>
<td>431.37</td>
<td>227.03</td>
<td>-907371.21</td>
<td>1005855.28</td>
</tr>
<tr class="even">
<td>2024-12-09</td>
<td>1913226.49</td>
<td>-784</td>
<td>0</td>
<td>-769</td>
<td>1213</td>
<td>-685</td>
<td>-1119</td>
<td>0</td>
<td>-457</td>
<td>-434</td>
<td>0</td>
<td>246.75</td>
<td>446.02</td>
<td>243.81</td>
<td>112.90</td>
<td>149.60</td>
<td>170.79</td>
<td>138.81</td>
<td>399.26</td>
<td>429.18</td>
<td>226.09</td>
<td>-906310.14</td>
<td>1006916.35</td>
</tr>
<tr class="odd">
<td>2024-12-10</td>
<td>1913226.49</td>
<td>-784</td>
<td>0</td>
<td>-769</td>
<td>1213</td>
<td>-685</td>
<td>-1119</td>
<td>0</td>
<td>-457</td>
<td>-434</td>
<td>0</td>
<td>247.77</td>
<td>443.33</td>
<td>242.86</td>
<td>112.67</td>
<td>149.23</td>
<td>172.28</td>
<td>135.07</td>
<td>388.39</td>
<td>422.59</td>
<td>225.04</td>
<td>-900244.47</td>
<td>1012982.02</td>
</tr>
<tr class="even">
<td>2024-12-11</td>
<td>1752148.30</td>
<td>0</td>
<td>0</td>
<td>-769</td>
<td>0</td>
<td>0</td>
<td>-1119</td>
<td>0</td>
<td>-457</td>
<td>-434</td>
<td>0</td>
<td>246.49</td>
<td>448.99</td>
<td>243.53</td>
<td>111.92</td>
<td>146.64</td>
<td>170.63</td>
<td>139.31</td>
<td>388.87</td>
<td>421.38</td>
<td>230.26</td>
<td>-738802.05</td>
<td>1013346.25</td>
</tr>
<tr class="odd">
<td>2024-12-12</td>
<td>1576093.62</td>
<td>0</td>
<td>0</td>
<td>-769</td>
<td>0</td>
<td>0</td>
<td>-1119</td>
<td>0</td>
<td>0</td>
<td>-434</td>
<td>0</td>
<td>247.96</td>
<td>449.56</td>
<td>241.53</td>
<td>111.82</td>
<td>146.24</td>
<td>170.85</td>
<td>137.34</td>
<td>380.78</td>
<td>414.42</td>
<td>228.97</td>
<td>-556776.00</td>
<td>1019317.62</td>
</tr>
<tr class="even">
<td>2024-12-13</td>
<td>1576093.62</td>
<td>0</td>
<td>0</td>
<td>-769</td>
<td>0</td>
<td>0</td>
<td>-1119</td>
<td>0</td>
<td>0</td>
<td>-434</td>
<td>0</td>
<td>248.13</td>
<td>447.27</td>
<td>239.94</td>
<td>110.84</td>
<td>146.62</td>
<td>171.06</td>
<td>134.25</td>
<td>380.51</td>
<td>416.98</td>
<td>227.46</td>
<td>-556899.32</td>
<td>1019194.30</td>
</tr>
<tr class="odd">
<td>2024-12-16</td>
<td>1576093.62</td>
<td>0</td>
<td>0</td>
<td>-769</td>
<td>0</td>
<td>0</td>
<td>-1119</td>
<td>0</td>
<td>0</td>
<td>-434</td>
<td>0</td>
<td>251.04</td>
<td>451.59</td>
<td>239.58</td>
<td>108.47</td>
<td>143.85</td>
<td>171.14</td>
<td>132.00</td>
<td>378.92</td>
<td>410.71</td>
<td>232.93</td>
<td>-553990.82</td>
<td>1022102.80</td>
</tr>
<tr class="even">
<td>2024-12-17</td>
<td>1576093.62</td>
<td>0</td>
<td>0</td>
<td>-769</td>
<td>0</td>
<td>0</td>
<td>-1119</td>
<td>0</td>
<td>0</td>
<td>-434</td>
<td>0</td>
<td>253.48</td>
<td>454.46</td>
<td>238.36</td>
<td>108.01</td>
<td>146.41</td>
<td>170.33</td>
<td>130.39</td>
<td>375.80</td>
<td>408.47</td>
<td>231.15</td>
<td>-551174.09</td>
<td>1024919.53</td>
</tr>
<tr class="odd">
<td>2024-12-18</td>
<td>1033756.10</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>248.05</td>
<td>437.39</td>
<td>230.37</td>
<td>106.42</td>
<td>144.75</td>
<td>169.08</td>
<td>128.91</td>
<td>363.89</td>
<td>393.82</td>
<td>220.52</td>
<td>0.00</td>
<td>1033756.10</td>
</tr>
<tr class="even">
<td>2024-12-19</td>
<td>1033756.10</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>249.79</td>
<td>437.03</td>
<td>232.96</td>
<td>105.51</td>
<td>143.58</td>
<td>169.19</td>
<td>130.68</td>
<td>360.37</td>
<td>385.02</td>
<td>223.29</td>
<td>0.00</td>
<td>1033756.10</td>
</tr>
<tr class="odd">
<td>2024-12-20</td>
<td>1033756.10</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>254.49</td>
<td>436.60</td>
<td>237.60</td>
<td>105.87</td>
<td>144.47</td>
<td>168.06</td>
<td>134.70</td>
<td>366.04</td>
<td>392.60</td>
<td>224.92</td>
<td>0.00</td>
<td>1033756.10</td>
</tr>
<tr class="even">
<td>2024-12-23</td>
<td>1033756.10</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>255.27</td>
<td>435.25</td>
<td>238.39</td>
<td>106.30</td>
<td>145.27</td>
<td>168.11</td>
<td>139.67</td>
<td>365.39</td>
<td>392.45</td>
<td>225.06</td>
<td>0.00</td>
<td>1033756.10</td>
</tr>
<tr class="odd">
<td>2024-12-24</td>
<td>1033756.10</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>258.20</td>
<td>439.33</td>
<td>242.31</td>
<td>106.40</td>
<td>145.85</td>
<td>168.94</td>
<td>140.22</td>
<td>367.57</td>
<td>396.14</td>
<td>229.05</td>
<td>0.00</td>
<td>1033756.10</td>
</tr>
<tr class="even">
<td>2024-12-26</td>
<td>1033756.10</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>259.02</td>
<td>438.11</td>
<td>243.14</td>
<td>106.49</td>
<td>145.58</td>
<td>170.16</td>
<td>139.93</td>
<td>367.12</td>
<td>395.14</td>
<td>227.05</td>
<td>0.00</td>
<td>1033756.10</td>
</tr>
<tr class="odd">
<td>2024-12-27</td>
<td>1033756.10</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>255.59</td>
<td>430.53</td>
<td>241.17</td>
<td>106.48</td>
<td>145.05</td>
<td>169.53</td>
<td>137.01</td>
<td>364.86</td>
<td>392.86</td>
<td>223.75</td>
<td>0.00</td>
<td>1033756.10</td>
</tr>
<tr class="even">
<td>2024-12-30</td>
<td>1033756.10</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>252.20</td>
<td>424.83</td>
<td>239.32</td>
<td>105.76</td>
<td>143.34</td>
<td>167.09</td>
<td>137.49</td>
<td>363.01</td>
<td>389.43</td>
<td>221.30</td>
<td>0.00</td>
<td>1033756.10</td>
</tr>
<tr class="odd">
<td>2024-12-31</td>
<td>1033756.10</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>250.42</td>
<td>421.50</td>
<td>239.71</td>
<td>107.57</td>
<td>144.62</td>
<td>167.65</td>
<td>134.29</td>
<td>362.76</td>
<td>388.99</td>
<td>219.39</td>
<td>0.00</td>
<td>1033756.10</td>
</tr>
<tr class="even">
<td>2025-01-02</td>
<td>34254.62</td>
<td>-509</td>
<td>340</td>
<td>471</td>
<td>1151</td>
<td>628</td>
<td>675</td>
<td>1048</td>
<td>396</td>
<td>335</td>
<td>540</td>
<td>243.85</td>
<td>418.58</td>
<td>240.00</td>
<td>107.31</td>
<td>144.02</td>
<td>165.98</td>
<td>138.31</td>
<td>359.77</td>
<td>388.46</td>
<td>220.22</td>
<td>993703.12</td>
<td>1027957.74</td>
</tr>
<tr class="odd">
<td>2025-01-03</td>
<td>185093.26</td>
<td>-509</td>
<td>340</td>
<td>471</td>
<td>1151</td>
<td>628</td>
<td>675</td>
<td>0</td>
<td>396</td>
<td>335</td>
<td>540</td>
<td>243.36</td>
<td>423.35</td>
<td>243.28</td>
<td>107.86</td>
<td>144.19</td>
<td>165.13</td>
<td>144.47</td>
<td>363.79</td>
<td>389.18</td>
<td>224.19</td>
<td>856313.31</td>
<td>1041406.57</td>
</tr>
<tr class="even">
<td>2025-01-06</td>
<td>185093.26</td>
<td>-509</td>
<td>340</td>
<td>471</td>
<td>1151</td>
<td>628</td>
<td>675</td>
<td>0</td>
<td>396</td>
<td>335</td>
<td>540</td>
<td>245.00</td>
<td>427.85</td>
<td>240.85</td>
<td>107.74</td>
<td>143.66</td>
<td>160.60</td>
<td>149.43</td>
<td>364.20</td>
<td>389.37</td>
<td>227.61</td>
<td>854408.12</td>
<td>1039501.38</td>
</tr>
<tr class="odd">
<td>2025-01-07</td>
<td>185093.26</td>
<td>-509</td>
<td>340</td>
<td>471</td>
<td>1151</td>
<td>628</td>
<td>675</td>
<td>0</td>
<td>396</td>
<td>335</td>
<td>540</td>
<td>242.21</td>
<td>422.37</td>
<td>243.17</td>
<td>108.75</td>
<td>146.23</td>
<td>161.30</td>
<td>140.14</td>
<td>363.00</td>
<td>384.23</td>
<td>222.11</td>
<td>853139.62</td>
<td>1038232.88</td>
</tr>
<tr class="even">
<td>2025-01-08</td>
<td>185093.26</td>
<td>-509</td>
<td>340</td>
<td>471</td>
<td>1151</td>
<td>628</td>
<td>675</td>
<td>0</td>
<td>396</td>
<td>335</td>
<td>540</td>
<td>242.70</td>
<td>424.56</td>
<td>243.13</td>
<td>106.93</td>
<td>142.27</td>
<td>162.10</td>
<td>140.11</td>
<td>361.07</td>
<td>387.20</td>
<td>222.13</td>
<td>849815.74</td>
<td>1034909.00</td>
</tr>
<tr class="odd">
<td>2025-01-10</td>
<td>172042.50</td>
<td>0</td>
<td>340</td>
<td>471</td>
<td>1151</td>
<td>628</td>
<td>0</td>
<td>0</td>
<td>396</td>
<td>335</td>
<td>540</td>
<td>236.85</td>
<td>418.95</td>
<td>239.87</td>
<td>106.54</td>
<td>142.06</td>
<td>158.56</td>
<td>135.91</td>
<td>351.00</td>
<td>389.89</td>
<td>218.94</td>
<td>855099.74</td>
<td>1027142.24</td>
</tr>
<tr class="even">
<td>2025-01-13</td>
<td>172042.50</td>
<td>0</td>
<td>340</td>
<td>471</td>
<td>1151</td>
<td>628</td>
<td>0</td>
<td>0</td>
<td>396</td>
<td>335</td>
<td>540</td>
<td>234.40</td>
<td>417.19</td>
<td>244.21</td>
<td>109.29</td>
<td>144.47</td>
<td>158.84</td>
<td>133.23</td>
<td>362.50</td>
<td>389.18</td>
<td>218.46</td>
<td>865281.16</td>
<td>1037323.66</td>
</tr>
<tr class="odd">
<td>2025-01-14</td>
<td>172042.50</td>
<td>0</td>
<td>340</td>
<td>471</td>
<td>1151</td>
<td>628</td>
<td>0</td>
<td>0</td>
<td>396</td>
<td>335</td>
<td>540</td>
<td>233.28</td>
<td>415.67</td>
<td>247.47</td>
<td>109.72</td>
<td>144.75</td>
<td>159.74</td>
<td>131.76</td>
<td>371.57</td>
<td>392.78</td>
<td>217.76</td>
<td>871390.31</td>
<td>1043432.81</td>
</tr>
<tr class="even">
<td>2025-01-15</td>
<td>172042.50</td>
<td>0</td>
<td>340</td>
<td>471</td>
<td>1151</td>
<td>628</td>
<td>0</td>
<td>0</td>
<td>396</td>
<td>335</td>
<td>540</td>
<td>237.87</td>
<td>426.31</td>
<td>252.35</td>
<td>111.51</td>
<td>144.97</td>
<td>159.65</td>
<td>136.24</td>
<td>374.89</td>
<td>406.09</td>
<td>223.35</td>
<td>888297.01</td>
<td>1060339.51</td>
</tr>
<tr class="odd">
<td>2025-01-16</td>
<td>292623.21</td>
<td>0</td>
<td>340</td>
<td>0</td>
<td>1151</td>
<td>628</td>
<td>0</td>
<td>0</td>
<td>396</td>
<td>335</td>
<td>540</td>
<td>228.26</td>
<td>424.58</td>
<td>254.27</td>
<td>111.32</td>
<td>147.77</td>
<td>160.50</td>
<td>133.57</td>
<td>380.55</td>
<td>409.33</td>
<td>220.66</td>
<td>772265.83</td>
<td>1064889.04</td>
</tr>
<tr class="even">
<td>2025-01-17</td>
<td>445621.77</td>
<td>0</td>
<td>340</td>
<td>0</td>
<td>1151</td>
<td>628</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>335</td>
<td>540</td>
<td>229.98</td>
<td>429.03</td>
<td>259.16</td>
<td>112.32</td>
<td>147.03</td>
<td>161.13</td>
<td>137.71</td>
<td>386.02</td>
<td>409.38</td>
<td>225.94</td>
<td>626635.26</td>
<td>1072257.03</td>
</tr>
<tr class="odd">
<td>2025-01-21</td>
<td>585135.87</td>
<td>0</td>
<td>340</td>
<td>0</td>
<td>1151</td>
<td>628</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>540</td>
<td>222.64</td>
<td>428.50</td>
<td>263.03</td>
<td>111.47</td>
<td>148.15</td>
<td>161.72</td>
<td>140.83</td>
<td>398.36</td>
<td>418.43</td>
<td>230.71</td>
<td>491613.57</td>
<td>1076749.44</td>
</tr>
<tr class="even">
<td>2025-01-22</td>
<td>712073.67</td>
<td>0</td>
<td>340</td>
<td>0</td>
<td>1151</td>
<td>628</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>223.83</td>
<td>446.20</td>
<td>262.84</td>
<td>109.53</td>
<td>145.27</td>
<td>164.74</td>
<td>147.07</td>
<td>397.61</td>
<td>410.10</td>
<td>235.01</td>
<td>369006.59</td>
<td>1081080.26</td>
</tr>
<tr class="odd">
<td>2025-01-23</td>
<td>712073.67</td>
<td>0</td>
<td>340</td>
<td>0</td>
<td>1151</td>
<td>628</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>223.66</td>
<td>446.71</td>
<td>265.95</td>
<td>110.15</td>
<td>146.64</td>
<td>166.15</td>
<td>147.22</td>
<td>406.40</td>
<td>414.39</td>
<td>235.42</td>
<td>370753.97</td>
<td>1082827.64</td>
</tr>
<tr class="even">
<td>2025-01-24</td>
<td>712073.67</td>
<td>0</td>
<td>340</td>
<td>0</td>
<td>1151</td>
<td>628</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>222.78</td>
<td>444.06</td>
<td>264.84</td>
<td>108.66</td>
<td>146.82</td>
<td>164.12</td>
<td>142.62</td>
<td>407.63</td>
<td>414.50</td>
<td>234.85</td>
<td>368251.02</td>
<td>1080324.69</td>
</tr>
<tr class="odd">
<td>2025-01-27</td>
<td>712073.67</td>
<td>0</td>
<td>340</td>
<td>0</td>
<td>1151</td>
<td>628</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>229.86</td>
<td>434.56</td>
<td>265.85</td>
<td>110.17</td>
<td>152.89</td>
<td>169.66</td>
<td>118.42</td>
<td>394.98</td>
<td>424.87</td>
<td>235.42</td>
<td>370570.99</td>
<td>1082644.66</td>
</tr>
<tr class="even">
<td>2025-01-28</td>
<td>712073.67</td>
<td>0</td>
<td>340</td>
<td>0</td>
<td>1151</td>
<td>628</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>238.26</td>
<td>447.20</td>
<td>267.14</td>
<td>108.04</td>
<td>150.38</td>
<td>166.19</td>
<td>128.99</td>
<td>390.29</td>
<td>418.83</td>
<td>238.15</td>
<td>370840.68</td>
<td>1082914.35</td>
</tr>
<tr class="odd">
<td>2025-01-29</td>
<td>712073.67</td>
<td>0</td>
<td>340</td>
<td>0</td>
<td>1151</td>
<td>628</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>239.36</td>
<td>442.33</td>
<td>266.58</td>
<td>108.67</td>
<td>151.15</td>
<td>166.23</td>
<td>123.70</td>
<td>393.23</td>
<td>413.42</td>
<td>237.07</td>
<td>370393.57</td>
<td>1082467.24</td>
</tr>
<tr class="even">
<td>2025-01-30</td>
<td>808791.95</td>
<td>0</td>
<td>340</td>
<td>0</td>
<td>1151</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>237.59</td>
<td>414.99</td>
<td>268.23</td>
<td>109.57</td>
<td>152.87</td>
<td>167.41</td>
<td>124.65</td>
<td>374.98</td>
<td>414.50</td>
<td>234.64</td>
<td>267211.67</td>
<td>1076003.62</td>
</tr>
<tr class="odd">
<td>2025-01-31</td>
<td>1072873.68</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>236.00</td>
<td>415.06</td>
<td>267.30</td>
<td>106.83</td>
<td>152.15</td>
<td>165.99</td>
<td>120.07</td>
<td>371.44</td>
<td>411.98</td>
<td>237.68</td>
<td>0.00</td>
<td>1072873.68</td>
</tr>
<tr class="even">
<td>2025-02-03</td>
<td>2072238.38</td>
<td>1041</td>
<td>860</td>
<td>-1332</td>
<td>-2002</td>
<td>-2055</td>
<td>-1447</td>
<td>3358</td>
<td>-672</td>
<td>-705</td>
<td>-1424</td>
<td>228.01</td>
<td>410.92</td>
<td>266.81</td>
<td>107.09</td>
<td>151.87</td>
<td>168.76</td>
<td>116.66</td>
<td>361.55</td>
<td>408.76</td>
<td>237.42</td>
<td>-1012803.26</td>
<td>1059435.12</td>
</tr>
<tr class="odd">
<td>2025-02-04</td>
<td>2072238.38</td>
<td>1041</td>
<td>860</td>
<td>-1332</td>
<td>-2002</td>
<td>-2055</td>
<td>-1447</td>
<td>3358</td>
<td>-672</td>
<td>-705</td>
<td>-1424</td>
<td>232.80</td>
<td>412.37</td>
<td>267.94</td>
<td>109.96</td>
<td>153.49</td>
<td>168.13</td>
<td>118.65</td>
<td>361.95</td>
<td>411.49</td>
<td>242.06</td>
<td>-1018356.65</td>
<td>1053881.73</td>
</tr>
<tr class="even">
<td>2025-02-05</td>
<td>2488798.28</td>
<td>1041</td>
<td>860</td>
<td>-1332</td>
<td>-2002</td>
<td>-2055</td>
<td>-1447</td>
<td>0</td>
<td>-672</td>
<td>-705</td>
<td>-1424</td>
<td>232.47</td>
<td>413.29</td>
<td>270.43</td>
<td>109.88</td>
<td>154.69</td>
<td>169.01</td>
<td>124.83</td>
<td>358.85</td>
<td>413.82</td>
<td>236.17</td>
<td>-1414403.65</td>
<td>1074394.63</td>
</tr>
<tr class="odd">
<td>2025-02-06</td>
<td>2488798.28</td>
<td>1041</td>
<td>860</td>
<td>-1332</td>
<td>-2002</td>
<td>-2055</td>
<td>-1447</td>
<td>0</td>
<td>-672</td>
<td>-705</td>
<td>-1424</td>
<td>233.22</td>
<td>415.82</td>
<td>276.90</td>
<td>108.43</td>
<td>153.51</td>
<td>168.88</td>
<td>128.68</td>
<td>365.45</td>
<td>414.16</td>
<td>238.83</td>
<td>-1423011.97</td>
<td>1065786.31</td>
</tr>
<tr class="even">
<td>2025-02-07</td>
<td>2488798.28</td>
<td>1041</td>
<td>860</td>
<td>-1332</td>
<td>-2002</td>
<td>-2055</td>
<td>-1447</td>
<td>0</td>
<td>-672</td>
<td>-705</td>
<td>-1424</td>
<td>227.63</td>
<td>409.75</td>
<td>275.80</td>
<td>108.89</td>
<td>153.12</td>
<td>167.97</td>
<td>129.84</td>
<td>363.88</td>
<td>407.37</td>
<td>229.15</td>
<td>-1411762.55</td>
<td>1077035.73</td>
</tr>
<tr class="odd">
<td>2025-02-10</td>
<td>2488798.28</td>
<td>1041</td>
<td>860</td>
<td>-1332</td>
<td>-2002</td>
<td>-2055</td>
<td>-1447</td>
<td>0</td>
<td>-672</td>
<td>-705</td>
<td>-1424</td>
<td>227.65</td>
<td>412.22</td>
<td>271.04</td>
<td>110.97</td>
<td>154.24</td>
<td>167.53</td>
<td>133.57</td>
<td>363.22</td>
<td>413.99</td>
<td>233.14</td>
<td>-1419011.63</td>
<td>1069786.65</td>
</tr>
<tr class="even">
<td>2025-02-11</td>
<td>2488798.28</td>
<td>1041</td>
<td>860</td>
<td>-1332</td>
<td>-2002</td>
<td>-2055</td>
<td>-1447</td>
<td>0</td>
<td>-672</td>
<td>-705</td>
<td>-1424</td>
<td>232.62</td>
<td>411.44</td>
<td>274.99</td>
<td>111.67</td>
<td>156.13</td>
<td>169.43</td>
<td>132.80</td>
<td>362.23</td>
<td>416.36</td>
<td>232.76</td>
<td>-1428269.16</td>
<td>1060529.12</td>
</tr>
<tr class="odd">
<td>2025-02-12</td>
<td>2488798.28</td>
<td>1041</td>
<td>860</td>
<td>-1332</td>
<td>-2002</td>
<td>-2055</td>
<td>-1447</td>
<td>0</td>
<td>-672</td>
<td>-705</td>
<td>-1424</td>
<td>236.87</td>
<td>409.04</td>
<td>275.45</td>
<td>107.35</td>
<td>155.26</td>
<td>169.58</td>
<td>131.14</td>
<td>352.04</td>
<td>407.14</td>
<td>228.93</td>
<td>-1397500.49</td>
<td>1091297.79</td>
</tr>
<tr class="even">
<td>2025-02-13</td>
<td>2488798.28</td>
<td>1041</td>
<td>860</td>
<td>-1332</td>
<td>-2002</td>
<td>-2055</td>
<td>-1447</td>
<td>0</td>
<td>-672</td>
<td>-705</td>
<td>-1424</td>
<td>241.53</td>
<td>410.54</td>
<td>276.32</td>
<td>108.13</td>
<td>157.25</td>
<td>171.02</td>
<td>135.29</td>
<td>353.70</td>
<td>412.43</td>
<td>230.37</td>
<td>-1407148.49</td>
<td>1081649.79</td>
</tr>
<tr class="odd">
<td>2025-02-14</td>
<td>2488798.28</td>
<td>1041</td>
<td>860</td>
<td>-1332</td>
<td>-2002</td>
<td>-2055</td>
<td>-1447</td>
<td>0</td>
<td>-672</td>
<td>-705</td>
<td>-1424</td>
<td>244.60</td>
<td>408.43</td>
<td>276.59</td>
<td>108.24</td>
<td>156.15</td>
<td>162.89</td>
<td>138.85</td>
<td>353.32</td>
<td>409.50</td>
<td>228.68</td>
<td>-1387594.90</td>
<td>1101203.38</td>
</tr>
<tr class="even">
<td>2025-02-18</td>
<td>2488798.28</td>
<td>1041</td>
<td>860</td>
<td>-1332</td>
<td>-2002</td>
<td>-2055</td>
<td>-1447</td>
<td>0</td>
<td>-672</td>
<td>-705</td>
<td>-1424</td>
<td>244.47</td>
<td>409.64</td>
<td>279.95</td>
<td>110.14</td>
<td>154.99</td>
<td>165.43</td>
<td>139.40</td>
<td>354.00</td>
<td>403.31</td>
<td>226.65</td>
<td>-1389462.82</td>
<td>1099335.46</td>
</tr>
<tr class="odd">
<td>2025-02-19</td>
<td>2488798.28</td>
<td>1041</td>
<td>860</td>
<td>-1332</td>
<td>-2002</td>
<td>-2055</td>
<td>-1447</td>
<td>0</td>
<td>-672</td>
<td>-705</td>
<td>-1424</td>
<td>244.87</td>
<td>414.77</td>
<td>279.25</td>
<td>110.30</td>
<td>157.89</td>
<td>166.49</td>
<td>139.23</td>
<td>353.00</td>
<td>395.43</td>
<td>226.63</td>
<td>-1385259.98</td>
<td>1103538.30</td>
</tr>
<tr class="even">
<td>2025-02-20</td>
<td>2488798.28</td>
<td>1041</td>
<td>860</td>
<td>-1332</td>
<td>-2002</td>
<td>-2055</td>
<td>-1447</td>
<td>0</td>
<td>-672</td>
<td>-705</td>
<td>-1424</td>
<td>245.83</td>
<td>416.13</td>
<td>266.80</td>
<td>112.00</td>
<td>159.68</td>
<td>167.21</td>
<td>140.11</td>
<td>349.15</td>
<td>394.64</td>
<td>222.88</td>
<td>-1366147.16</td>
<td>1122651.12</td>
</tr>
<tr class="odd">
<td>2025-02-21</td>
<td>2103210.87</td>
<td>0</td>
<td>860</td>
<td>-1332</td>
<td>-2002</td>
<td>0</td>
<td>-1447</td>
<td>0</td>
<td>-672</td>
<td>-705</td>
<td>0</td>
<td>245.55</td>
<td>408.21</td>
<td>264.24</td>
<td>110.69</td>
<td>162.30</td>
<td>170.23</td>
<td>134.43</td>
<td>340.04</td>
<td>385.30</td>
<td>216.58</td>
<td>-968974.65</td>
<td>1134236.22</td>
</tr>
<tr class="even">
<td>2025-02-24</td>
<td>2103210.87</td>
<td>0</td>
<td>860</td>
<td>-1332</td>
<td>-2002</td>
<td>0</td>
<td>-1447</td>
<td>0</td>
<td>-672</td>
<td>-705</td>
<td>0</td>
<td>247.10</td>
<td>404.00</td>
<td>261.34</td>
<td>111.27</td>
<td>163.74</td>
<td>170.54</td>
<td>130.28</td>
<td>338.92</td>
<td>382.42</td>
<td>212.71</td>
<td>-967559.14</td>
<td>1135651.73</td>
</tr>
<tr class="odd">
<td>2025-02-25</td>
<td>2103210.87</td>
<td>0</td>
<td>860</td>
<td>-1332</td>
<td>-2002</td>
<td>0</td>
<td>-1447</td>
<td>0</td>
<td>-672</td>
<td>-705</td>
<td>0</td>
<td>247.04</td>
<td>397.90</td>
<td>257.40</td>
<td>109.73</td>
<td>166.09</td>
<td>172.65</td>
<td>126.63</td>
<td>342.36</td>
<td>393.29</td>
<td>212.80</td>
<td>-977502.18</td>
<td>1125708.69</td>
</tr>
<tr class="even">
<td>2025-02-26</td>
<td>2103210.87</td>
<td>0</td>
<td>860</td>
<td>-1332</td>
<td>-2002</td>
<td>0</td>
<td>-1447</td>
<td>0</td>
<td>-672</td>
<td>-705</td>
<td>0</td>
<td>240.36</td>
<td>399.73</td>
<td>258.79</td>
<td>109.46</td>
<td>163.08</td>
<td>171.30</td>
<td>131.28</td>
<td>342.58</td>
<td>390.48</td>
<td>214.35</td>
<td>-973452.66</td>
<td>1129758.21</td>
</tr>
<tr class="odd">
<td>2025-02-27</td>
<td>2103210.87</td>
<td>0</td>
<td>860</td>
<td>-1332</td>
<td>-2002</td>
<td>0</td>
<td>-1447</td>
<td>0</td>
<td>-672</td>
<td>-705</td>
<td>0</td>
<td>237.30</td>
<td>392.53</td>
<td>259.05</td>
<td>110.15</td>
<td>163.73</td>
<td>171.97</td>
<td>120.15</td>
<td>340.00</td>
<td>390.27</td>
<td>208.74</td>
<td>-980460.04</td>
<td>1122750.83</td>
</tr>
<tr class="even">
<td>2025-02-28</td>
<td>1106941.93</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>241.84</td>
<td>396.99</td>
<td>264.65</td>
<td>111.33</td>
<td>165.02</td>
<td>173.84</td>
<td>124.92</td>
<td>343.95</td>
<td>396.60</td>
<td>212.28</td>
<td>0.00</td>
<td>1106941.93</td>
</tr>
<tr class="odd">
<td>2025-03-03</td>
<td>106987.14</td>
<td>-2162</td>
<td>1334</td>
<td>1807</td>
<td>-3778</td>
<td>-3392</td>
<td>-3646</td>
<td>4457</td>
<td>1425</td>
<td>1363</td>
<td>2539</td>
<td>238.03</td>
<td>388.49</td>
<td>260.62</td>
<td>107.76</td>
<td>167.28</td>
<td>175.59</td>
<td>114.06</td>
<td>332.04</td>
<td>389.69</td>
<td>205.02</td>
<td>893048.63</td>
<td>1000035.77</td>
</tr>
<tr class="even">
<td>2025-03-04</td>
<td>106987.14</td>
<td>-2162</td>
<td>1334</td>
<td>1807</td>
<td>-3778</td>
<td>-3392</td>
<td>-3646</td>
<td>4457</td>
<td>1425</td>
<td>1363</td>
<td>2539</td>
<td>235.93</td>
<td>388.61</td>
<td>250.25</td>
<td>107.54</td>
<td>165.42</td>
<td>173.18</td>
<td>115.99</td>
<td>326.75</td>
<td>381.68</td>
<td>203.80</td>
<td>881986.01</td>
<td>988973.15</td>
</tr>
<tr class="odd">
<td>2025-03-05</td>
<td>106987.14</td>
<td>-2162</td>
<td>1334</td>
<td>1807</td>
<td>-3778</td>
<td>-3392</td>
<td>-3646</td>
<td>4457</td>
<td>1425</td>
<td>1363</td>
<td>2539</td>
<td>235.74</td>
<td>401.02</td>
<td>251.53</td>
<td>105.44</td>
<td>165.12</td>
<td>174.61</td>
<td>117.30</td>
<td>338.49</td>
<td>386.35</td>
<td>208.36</td>
<td>945513.53</td>
<td>1052500.67</td>
</tr>
<tr class="even">
<td>2025-03-06</td>
<td>601001.02</td>
<td>-2162</td>
<td>1334</td>
<td>1807</td>
<td>-3778</td>
<td>-3392</td>
<td>-3646</td>
<td>0</td>
<td>1425</td>
<td>1363</td>
<td>2539</td>
<td>235.33</td>
<td>396.89</td>
<td>246.54</td>
<td>107.62</td>
<td>165.83</td>
<td>174.66</td>
<td>110.57</td>
<td>341.01</td>
<td>381.73</td>
<td>200.70</td>
<td>376086.04</td>
<td>977087.06</td>
</tr>
<tr class="odd">
<td>2025-03-07</td>
<td>601001.02</td>
<td>-2162</td>
<td>1334</td>
<td>1807</td>
<td>-3778</td>
<td>-3392</td>
<td>-3646</td>
<td>0</td>
<td>1425</td>
<td>1363</td>
<td>2539</td>
<td>239.07</td>
<td>393.31</td>
<td>242.28</td>
<td>109.02</td>
<td>166.69</td>
<td>175.95</td>
<td>112.69</td>
<td>350.30</td>
<td>376.80</td>
<td>199.25</td>
<td>345454.07</td>
<td>946455.09</td>
</tr>
<tr class="even">
<td>2025-03-10</td>
<td>1510733.18</td>
<td>-2162</td>
<td>1334</td>
<td>0</td>
<td>-3778</td>
<td>-3392</td>
<td>-3646</td>
<td>0</td>
<td>1425</td>
<td>1363</td>
<td>0</td>
<td>227.48</td>
<td>380.16</td>
<td>232.22</td>
<td>111.80</td>
<td>167.70</td>
<td>176.26</td>
<td>106.98</td>
<td>345.21</td>
<td>374.65</td>
<td>194.54</td>
<td>-615968.88</td>
<td>894764.30</td>
</tr>
<tr class="odd">
<td>2025-03-11</td>
<td>1510733.18</td>
<td>-2162</td>
<td>1334</td>
<td>0</td>
<td>-3778</td>
<td>-3392</td>
<td>-3646</td>
<td>0</td>
<td>1425</td>
<td>1363</td>
<td>0</td>
<td>220.84</td>
<td>380.45</td>
<td>229.14</td>
<td>109.16</td>
<td>165.86</td>
<td>173.12</td>
<td>108.76</td>
<td>339.77</td>
<td>368.16</td>
<td>196.59</td>
<td>-590160.57</td>
<td>920572.61</td>
</tr>
<tr class="even">
<td>2025-03-12</td>
<td>1043524.98</td>
<td>0</td>
<td>1334</td>
<td>0</td>
<td>-3778</td>
<td>-3392</td>
<td>-3646</td>
<td>0</td>
<td>1425</td>
<td>1363</td>
<td>0</td>
<td>216.98</td>
<td>383.27</td>
<td>227.90</td>
<td>109.13</td>
<td>162.85</td>
<td>168.37</td>
<td>115.74</td>
<td>338.13</td>
<td>364.73</td>
<td>198.89</td>
<td>-88312.94</td>
<td>955212.04</td>
</tr>
<tr class="odd">
<td>2025-03-13</td>
<td>1527103.75</td>
<td>0</td>
<td>1334</td>
<td>0</td>
<td>-3778</td>
<td>-3392</td>
<td>-3646</td>
<td>0</td>
<td>1425</td>
<td>0</td>
<td>0</td>
<td>209.68</td>
<td>378.77</td>
<td>225.19</td>
<td>108.67</td>
<td>162.99</td>
<td>168.59</td>
<td>115.58</td>
<td>333.31</td>
<td>347.25</td>
<td>193.89</td>
<td>-597850.55</td>
<td>929253.20</td>
</tr>
<tr class="even">
<td>2025-03-14</td>
<td>1527103.75</td>
<td>0</td>
<td>1334</td>
<td>0</td>
<td>-3778</td>
<td>-3392</td>
<td>-3646</td>
<td>0</td>
<td>1425</td>
<td>0</td>
<td>0</td>
<td>213.49</td>
<td>388.56</td>
<td>232.44</td>
<td>111.90</td>
<td>162.81</td>
<td>167.97</td>
<td>121.67</td>
<td>339.64</td>
<td>351.31</td>
<td>197.95</td>
<td>-585102.30</td>
<td>942001.45</td>
</tr>
<tr class="odd">
<td>2025-03-17</td>
<td>1527103.75</td>
<td>0</td>
<td>1334</td>
<td>0</td>
<td>-3778</td>
<td>-3392</td>
<td>-3646</td>
<td>0</td>
<td>1425</td>
<td>0</td>
<td>0</td>
<td>214.00</td>
<td>388.70</td>
<td>233.93</td>
<td>113.76</td>
<td>162.84</td>
<td>169.76</td>
<td>119.53</td>
<td>342.64</td>
<td>354.13</td>
<td>195.74</td>
<td>-594295.72</td>
<td>932808.03</td>
</tr>
<tr class="even">
<td>2025-03-18</td>
<td>1527103.75</td>
<td>0</td>
<td>1334</td>
<td>0</td>
<td>-3778</td>
<td>-3392</td>
<td>-3646</td>
<td>0</td>
<td>1425</td>
<td>0</td>
<td>0</td>
<td>212.69</td>
<td>383.52</td>
<td>234.97</td>
<td>113.64</td>
<td>164.25</td>
<td>167.71</td>
<td>115.43</td>
<td>336.71</td>
<td>349.57</td>
<td>192.82</td>
<td>-606511.15</td>
<td>920592.60</td>
</tr>
<tr class="odd">
<td>2025-03-19</td>
<td>1527103.75</td>
<td>0</td>
<td>1334</td>
<td>0</td>
<td>-3778</td>
<td>-3392</td>
<td>-3646</td>
<td>0</td>
<td>1425</td>
<td>0</td>
<td>0</td>
<td>215.24</td>
<td>387.82</td>
<td>239.11</td>
<td>115.41</td>
<td>162.99</td>
<td>168.57</td>
<td>117.52</td>
<td>338.62</td>
<td>353.42</td>
<td>195.54</td>
<td>-603601.90</td>
<td>923501.85</td>
</tr>
<tr class="even">
<td>2025-03-20</td>
<td>1527103.75</td>
<td>0</td>
<td>1334</td>
<td>0</td>
<td>-3778</td>
<td>-3392</td>
<td>-3646</td>
<td>0</td>
<td>1425</td>
<td>0</td>
<td>0</td>
<td>214.10</td>
<td>386.84</td>
<td>239.01</td>
<td>115.90</td>
<td>163.02</td>
<td>167.55</td>
<td>118.53</td>
<td>336.25</td>
<td>355.52</td>
<td>194.95</td>
<td>-606520.53</td>
<td>920583.22</td>
</tr>
<tr class="odd">
<td>2025-03-21</td>
<td>1527103.75</td>
<td>0</td>
<td>1334</td>
<td>0</td>
<td>-3778</td>
<td>-3392</td>
<td>-3646</td>
<td>0</td>
<td>1425</td>
<td>0</td>
<td>0</td>
<td>218.27</td>
<td>391.26</td>
<td>241.63</td>
<td>115.50</td>
<td>163.63</td>
<td>166.69</td>
<td>117.70</td>
<td>335.78</td>
<td>351.15</td>
<td>196.21</td>
<td>-598716.36</td>
<td>928387.39</td>
</tr>
<tr class="even">
<td>2025-03-24</td>
<td>1527103.75</td>
<td>0</td>
<td>1334</td>
<td>0</td>
<td>-3778</td>
<td>-3392</td>
<td>-3646</td>
<td>0</td>
<td>1425</td>
<td>0</td>
<td>0</td>
<td>220.73</td>
<td>393.08</td>
<td>248.06</td>
<td>115.80</td>
<td>163.29</td>
<td>165.65</td>
<td>121.41</td>
<td>341.67</td>
<td>363.77</td>
<td>203.26</td>
<td>-584083.51</td>
<td>943020.24</td>
</tr>
<tr class="odd">
<td>2025-03-25</td>
<td>1527103.75</td>
<td>0</td>
<td>1334</td>
<td>0</td>
<td>-3778</td>
<td>-3392</td>
<td>-3646</td>
<td>0</td>
<td>1425</td>
<td>0</td>
<td>0</td>
<td>223.75</td>
<td>395.16</td>
<td>251.13</td>
<td>116.59</td>
<td>161.02</td>
<td>162.85</td>
<td>120.69</td>
<td>342.62</td>
<td>360.99</td>
<td>205.71</td>
<td>-565031.02</td>
<td>962072.73</td>
</tr>
<tr class="even">
<td>2025-03-26</td>
<td>1527103.75</td>
<td>0</td>
<td>1334</td>
<td>0</td>
<td>-3778</td>
<td>-3392</td>
<td>-3646</td>
<td>0</td>
<td>1425</td>
<td>0</td>
<td>0</td>
<td>221.53</td>
<td>389.97</td>
<td>251.03</td>
<td>118.27</td>
<td>161.72</td>
<td>166.58</td>
<td>113.76</td>
<td>341.11</td>
<td>362.13</td>
<td>201.13</td>
<td>-596427.25</td>
<td>930676.50</td>
</tr>
<tr class="odd">
<td>2025-03-27</td>
<td>1527103.75</td>
<td>0</td>
<td>1334</td>
<td>0</td>
<td>-3778</td>
<td>-3392</td>
<td>-3646</td>
<td>0</td>
<td>1425</td>
<td>0</td>
<td>0</td>
<td>223.85</td>
<td>390.58</td>
<td>248.12</td>
<td>117.89</td>
<td>163.13</td>
<td>168.71</td>
<td>111.43</td>
<td>339.30</td>
<td>362.73</td>
<td>201.36</td>
<td>-609305.82</td>
<td>917797.93</td>
</tr>
<tr class="even">
<td>2025-03-28</td>
<td>1527103.75</td>
<td>0</td>
<td>1334</td>
<td>0</td>
<td>-3778</td>
<td>-3392</td>
<td>-3646</td>
<td>0</td>
<td>1425</td>
<td>0</td>
<td>0</td>
<td>217.90</td>
<td>378.80</td>
<td>242.85</td>
<td>117.73</td>
<td>163.71</td>
<td>168.03</td>
<td>109.67</td>
<td>329.69</td>
<td>358.15</td>
<td>192.72</td>
<td>-637598.19</td>
<td>889505.56</td>
</tr>
<tr class="odd">
<td>2025-03-31</td>
<td>864640.87</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>222.13</td>
<td>375.39</td>
<td>245.30</td>
<td>118.93</td>
<td>165.84</td>
<td>170.42</td>
<td>108.38</td>
<td>329.80</td>
<td>366.49</td>
<td>190.26</td>
<td>0.00</td>
<td>864640.87</td>
</tr>
<tr class="even">
<td>2025-04-01</td>
<td>-135084.10</td>
<td>1038</td>
<td>572</td>
<td>-564</td>
<td>-2566</td>
<td>1136</td>
<td>1231</td>
<td>2777</td>
<td>-614</td>
<td>489</td>
<td>1750</td>
<td>223.19</td>
<td>382.19</td>
<td>243.66</td>
<td>119.04</td>
<td>153.25</td>
<td>170.56</td>
<td>110.15</td>
<td>330.57</td>
<td>365.52</td>
<td>192.17</td>
<td>1009407.73</td>
<td>874323.63</td>
</tr>
<tr class="odd">
<td>2025-04-02</td>
<td>209875.90</td>
<td>1038</td>
<td>572</td>
<td>-564</td>
<td>-2566</td>
<td>1136</td>
<td>1231</td>
<td>2777</td>
<td>-614</td>
<td>489</td>
<td>0</td>
<td>223.89</td>
<td>382.14</td>
<td>245.82</td>
<td>118.67</td>
<td>155.36</td>
<td>169.50</td>
<td>110.42</td>
<td>334.66</td>
<td>370.89</td>
<td>196.01</td>
<td>675495.97</td>
<td>885371.87</td>
</tr>
<tr class="even">
<td>2025-04-03</td>
<td>98809.68</td>
<td>0</td>
<td>572</td>
<td>0</td>
<td>0</td>
<td>1136</td>
<td>1231</td>
<td>0</td>
<td>0</td>
<td>489</td>
<td>0</td>
<td>203.19</td>
<td>373.11</td>
<td>228.69</td>
<td>112.43</td>
<td>159.82</td>
<td>172.39</td>
<td>101.80</td>
<td>305.76</td>
<td>355.91</td>
<td>178.41</td>
<td>781226.52</td>
<td>880036.20</td>
</tr>
<tr class="odd">
<td>2025-04-04</td>
<td>98809.68</td>
<td>0</td>
<td>572</td>
<td>0</td>
<td>0</td>
<td>1136</td>
<td>1231</td>
<td>0</td>
<td>0</td>
<td>489</td>
<td>0</td>
<td>188.38</td>
<td>359.84</td>
<td>210.28</td>
<td>104.34</td>
<td>153.24</td>
<td>163.75</td>
<td>94.31</td>
<td>288.08</td>
<td>353.90</td>
<td>171.00</td>
<td>754542.47</td>
<td>853352.15</td>
</tr>
<tr class="even">
<td>2025-04-07</td>
<td>833245.71</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>181.46</td>
<td>357.86</td>
<td>214.44</td>
<td>102.94</td>
<td>150.62</td>
<td>160.23</td>
<td>97.64</td>
<td>280.06</td>
<td>341.51</td>
<td>175.26</td>
<td>0.00</td>
<td>833245.71</td>
</tr>
<tr class="odd">
<td>2025-04-08</td>
<td>833245.71</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>172.42</td>
<td>354.56</td>
<td>216.87</td>
<td>100.77</td>
<td>150.00</td>
<td>158.39</td>
<td>96.30</td>
<td>273.94</td>
<td>335.24</td>
<td>170.66</td>
<td>0.00</td>
<td>833245.71</td>
</tr>
<tr class="even">
<td>2025-04-09</td>
<td>833245.71</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>198.85</td>
<td>390.49</td>
<td>234.34</td>
<td>105.80</td>
<td>150.97</td>
<td>162.32</td>
<td>114.33</td>
<td>301.01</td>
<td>355.39</td>
<td>191.10</td>
<td>0.00</td>
<td>833245.71</td>
</tr>
<tr class="odd">
<td>2025-04-10</td>
<td>833245.71</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>190.42</td>
<td>381.35</td>
<td>227.11</td>
<td>99.93</td>
<td>148.69</td>
<td>163.56</td>
<td>107.57</td>
<td>289.16</td>
<td>353.62</td>
<td>181.22</td>
<td>0.00</td>
<td>833245.71</td>
</tr>
<tr class="even">
<td>2025-04-11</td>
<td>833245.71</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>198.15</td>
<td>388.45</td>
<td>236.20</td>
<td>103.14</td>
<td>151.73</td>
<td>166.91</td>
<td>110.93</td>
<td>293.45</td>
<td>353.86</td>
<td>184.87</td>
<td>0.00</td>
<td>833245.71</td>
</tr>
<tr class="odd">
<td>2025-04-14</td>
<td>833245.71</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>202.52</td>
<td>387.81</td>
<td>234.72</td>
<td>103.39</td>
<td>154.36</td>
<td>169.13</td>
<td>110.71</td>
<td>298.12</td>
<td>357.20</td>
<td>182.12</td>
<td>0.00</td>
<td>833245.71</td>
</tr>
<tr class="even">
<td>2025-04-15</td>
<td>833245.71</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>202.14</td>
<td>385.73</td>
<td>233.13</td>
<td>103.10</td>
<td>153.62</td>
<td>168.47</td>
<td>112.20</td>
<td>293.43</td>
<td>354.11</td>
<td>179.59</td>
<td>0.00</td>
<td>833245.71</td>
</tr>
<tr class="odd">
<td>2025-04-16</td>
<td>833245.71</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>194.27</td>
<td>371.61</td>
<td>229.61</td>
<td>104.19</td>
<td>153.91</td>
<td>166.39</td>
<td>104.49</td>
<td>290.14</td>
<td>345.99</td>
<td>174.33</td>
<td>0.00</td>
<td>833245.71</td>
</tr>
<tr class="even">
<td>2025-04-17</td>
<td>833245.71</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>196.98</td>
<td>367.78</td>
<td>231.96</td>
<td>106.92</td>
<td>157.47</td>
<td>170.63</td>
<td>101.49</td>
<td>294.25</td>
<td>355.06</td>
<td>172.61</td>
<td>0.00</td>
<td>833245.71</td>
</tr>
<tr class="odd">
<td>2025-04-21</td>
<td>833245.71</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>193.16</td>
<td>359.12</td>
<td>228.99</td>
<td>105.35</td>
<td>156.92</td>
<td>165.75</td>
<td>96.91</td>
<td>284.74</td>
<td>346.90</td>
<td>167.32</td>
<td>0.00</td>
<td>833245.71</td>
</tr>
<tr class="even">
<td>2025-04-22</td>
<td>833245.71</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>199.74</td>
<td>366.82</td>
<td>235.59</td>
<td>108.30</td>
<td>157.75</td>
<td>167.88</td>
<td>98.89</td>
<td>291.17</td>
<td>354.43</td>
<td>173.18</td>
<td>0.00</td>
<td>833245.71</td>
</tr>
<tr class="odd">
<td>2025-04-23</td>
<td>833245.71</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>204.60</td>
<td>374.39</td>
<td>240.88</td>
<td>107.37</td>
<td>155.38</td>
<td>165.73</td>
<td>102.71</td>
<td>295.77</td>
<td>356.42</td>
<td>180.60</td>
<td>0.00</td>
<td>833245.71</td>
</tr>
<tr class="even">
<td>2025-04-24</td>
<td>833245.71</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>208.37</td>
<td>387.30</td>
<td>244.64</td>
<td>108.63</td>
<td>154.93</td>
<td>159.53</td>
<td>106.43</td>
<td>306.86</td>
<td>359.64</td>
<td>186.54</td>
<td>0.00</td>
<td>833245.71</td>
</tr>
<tr class="odd">
<td>2025-04-25</td>
<td>833245.71</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>209.28</td>
<td>391.85</td>
<td>243.55</td>
<td>108.57</td>
<td>154.58</td>
<td>161.02</td>
<td>111.01</td>
<td>306.45</td>
<td>357.58</td>
<td>188.99</td>
<td>0.00</td>
<td>833245.71</td>
</tr>
<tr class="even">
<td>2025-04-28</td>
<td>833245.71</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>210.14</td>
<td>391.16</td>
<td>243.22</td>
<td>108.63</td>
<td>155.35</td>
<td>161.85</td>
<td>108.73</td>
<td>307.06</td>
<td>356.92</td>
<td>187.70</td>
<td>0.00</td>
<td>833245.71</td>
</tr>
<tr class="odd">
<td>2025-04-29</td>
<td>833245.71</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>211.21</td>
<td>394.04</td>
<td>244.62</td>
<td>108.36</td>
<td>155.91</td>
<td>162.26</td>
<td>109.02</td>
<td>307.40</td>
<td>359.00</td>
<td>187.39</td>
<td>0.00</td>
<td>833245.71</td>
</tr>
<tr class="even">
<td>2025-04-30</td>
<td>833245.71</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>210.77</td>
<td>390.06</td>
<td>242.25</td>
<td>105.04</td>
<td>155.81</td>
<td>161.97</td>
<td>106.95</td>
<td>303.57</td>
<td>357.69</td>
<td>181.88</td>
<td>0.00</td>
<td>833245.71</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<script>
document.addEventListener("DOMContentLoaded", function () {
  const input = document.getElementById("ledger-search");
  input.addEventListener("keyup", function () {
    const filter = input.value.toLowerCase();
    const rows = document.querySelectorAll("#ledger-table tbody tr");
    rows.forEach(row => {
      const dateCell = row.cells[0]?.textContent?.toLowerCase() || "";
      if (dateCell.includes(filter)) {
        row.style.display = "";
      } else {
        row.style.display = "none";
      }
    });
  });
});
</script>
</section>
<section id="after-controlling-lever-1" class="level5">
<h5 class="anchored" data-anchor-id="after-controlling-lever-1"><strong>After Controlling Lever</strong></h5>
<p><input type="text" id="ledger-search" placeholder="Search by Date(e.g., 2025-04-15)" style="padding: 5px; margin-bottom: 10px; width: 300px;"></p>
<div style="max-height: 400px; overflow: auto; border: 1px solid #ccc; border-radius: 10px; padding: 10px;">
<div id="eed177bd" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display">
<table id="ledger-table" class="dataframe table table-striped caption-top table-sm small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Date</th>
<th data-quarto-table-cell-role="th">Cash</th>
<th data-quarto-table-cell-role="th">AAPL Qty</th>
<th data-quarto-table-cell-role="th">MSFT Qty</th>
<th data-quarto-table-cell-role="th">JPM Qty</th>
<th data-quarto-table-cell-role="th">XOM Qty</th>
<th data-quarto-table-cell-role="th">JNJ Qty</th>
<th data-quarto-table-cell-role="th">PG Qty</th>
<th data-quarto-table-cell-role="th">NVDA Qty</th>
<th data-quarto-table-cell-role="th">CAT Qty</th>
<th data-quarto-table-cell-role="th">HD Qty</th>
<th data-quarto-table-cell-role="th">AMZN Qty</th>
<th data-quarto-table-cell-role="th">AAPL Close</th>
<th data-quarto-table-cell-role="th">MSFT Close</th>
<th data-quarto-table-cell-role="th">JPM Close</th>
<th data-quarto-table-cell-role="th">XOM Close</th>
<th data-quarto-table-cell-role="th">JNJ Close</th>
<th data-quarto-table-cell-role="th">PG Close</th>
<th data-quarto-table-cell-role="th">NVDA Close</th>
<th data-quarto-table-cell-role="th">CAT Close</th>
<th data-quarto-table-cell-role="th">HD Close</th>
<th data-quarto-table-cell-role="th">AMZN Close</th>
<th data-quarto-table-cell-role="th">Portfolio Value</th>
<th data-quarto-table-cell-role="th">Market Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2024-11-01</td>
<td>451235.76</td>
<td>362</td>
<td>228</td>
<td>-813</td>
<td>0</td>
<td>462</td>
<td>628</td>
<td>551</td>
<td>310</td>
<td>274</td>
<td>388</td>
<td>222.91</td>
<td>410.37</td>
<td>222.94</td>
<td>114.95</td>
<td>160.13</td>
<td>165.10</td>
<td>135.40</td>
<td>379.63</td>
<td>392.59</td>
<td>197.93</td>
<td>547327.62</td>
<td>998563.38</td>
</tr>
<tr class="even">
<td>2024-11-04</td>
<td>451235.76</td>
<td>362</td>
<td>228</td>
<td>-813</td>
<td>0</td>
<td>462</td>
<td>628</td>
<td>551</td>
<td>310</td>
<td>274</td>
<td>388</td>
<td>222.01</td>
<td>408.46</td>
<td>219.78</td>
<td>118.61</td>
<td>158.24</td>
<td>165.08</td>
<td>136.05</td>
<td>376.52</td>
<td>395.57</td>
<td>195.78</td>
<td>547626.05</td>
<td>998861.81</td>
</tr>
<tr class="odd">
<td>2024-11-05</td>
<td>527698.03</td>
<td>362</td>
<td>228</td>
<td>-813</td>
<td>0</td>
<td>462</td>
<td>628</td>
<td>0</td>
<td>310</td>
<td>274</td>
<td>388</td>
<td>223.45</td>
<td>411.46</td>
<td>221.49</td>
<td>118.96</td>
<td>158.35</td>
<td>165.76</td>
<td>139.91</td>
<td>383.37</td>
<td>400.09</td>
<td>199.50</td>
<td>477760.75</td>
<td>1005458.78</td>
</tr>
<tr class="even">
<td>2024-11-06</td>
<td>744273.84</td>
<td>362</td>
<td>228</td>
<td>0</td>
<td>0</td>
<td>462</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>222.72</td>
<td>420.18</td>
<td>247.06</td>
<td>121.00</td>
<td>157.88</td>
<td>161.05</td>
<td>145.61</td>
<td>416.88</td>
<td>388.37</td>
<td>207.09</td>
<td>249366.24</td>
<td>993640.08</td>
</tr>
<tr class="odd">
<td>2024-11-07</td>
<td>922713.44</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>462</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>227.48</td>
<td>425.43</td>
<td>236.38</td>
<td>121.15</td>
<td>156.73</td>
<td>163.41</td>
<td>148.88</td>
<td>408.21</td>
<td>399.44</td>
<td>210.05</td>
<td>72409.26</td>
<td>995122.70</td>
</tr>
<tr class="even">
<td>2024-11-08</td>
<td>994836.26</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>226.96</td>
<td>422.54</td>
<td>236.98</td>
<td>121.11</td>
<td>155.47</td>
<td>167.71</td>
<td>147.63</td>
<td>393.37</td>
<td>405.90</td>
<td>208.18</td>
<td>0.00</td>
<td>994836.26</td>
</tr>
<tr class="odd">
<td>2024-11-11</td>
<td>994836.26</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>224.23</td>
<td>418.01</td>
<td>239.29</td>
<td>120.47</td>
<td>155.04</td>
<td>166.03</td>
<td>145.26</td>
<td>396.54</td>
<td>408.29</td>
<td>206.84</td>
<td>0.00</td>
<td>994836.26</td>
</tr>
<tr class="even">
<td>2024-11-12</td>
<td>994836.26</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>224.23</td>
<td>423.03</td>
<td>239.56</td>
<td>120.35</td>
<td>152.64</td>
<td>165.84</td>
<td>148.29</td>
<td>393.01</td>
<td>403.08</td>
<td>208.91</td>
<td>0.00</td>
<td>994836.26</td>
</tr>
<tr class="odd">
<td>2024-11-13</td>
<td>994836.26</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>225.12</td>
<td>425.20</td>
<td>241.16</td>
<td>121.47</td>
<td>153.24</td>
<td>166.58</td>
<td>146.27</td>
<td>387.07</td>
<td>410.19</td>
<td>214.10</td>
<td>0.00</td>
<td>994836.26</td>
</tr>
<tr class="even">
<td>2024-11-14</td>
<td>994836.26</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>228.22</td>
<td>426.89</td>
<td>241.87</td>
<td>120.56</td>
<td>151.87</td>
<td>167.08</td>
<td>146.76</td>
<td>387.36</td>
<td>405.72</td>
<td>211.48</td>
<td>0.00</td>
<td>994836.26</td>
</tr>
<tr class="odd">
<td>2024-11-15</td>
<td>994836.26</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>225.00</td>
<td>415.00</td>
<td>245.31</td>
<td>119.31</td>
<td>154.00</td>
<td>169.54</td>
<td>141.98</td>
<td>384.07</td>
<td>408.18</td>
<td>202.61</td>
<td>0.00</td>
<td>994836.26</td>
</tr>
<tr class="even">
<td>2024-11-18</td>
<td>994836.26</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>228.02</td>
<td>415.76</td>
<td>245.03</td>
<td>120.31</td>
<td>154.77</td>
<td>170.75</td>
<td>140.15</td>
<td>384.46</td>
<td>410.44</td>
<td>201.70</td>
<td>0.00</td>
<td>994836.26</td>
</tr>
<tr class="odd">
<td>2024-11-19</td>
<td>994836.26</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>228.28</td>
<td>417.79</td>
<td>243.09</td>
<td>118.63</td>
<td>153.00</td>
<td>170.76</td>
<td>147.01</td>
<td>382.33</td>
<td>406.80</td>
<td>204.61</td>
<td>0.00</td>
<td>994836.26</td>
</tr>
<tr class="even">
<td>2024-11-20</td>
<td>994836.26</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>229.00</td>
<td>415.49</td>
<td>240.78</td>
<td>120.32</td>
<td>153.11</td>
<td>170.89</td>
<td>145.89</td>
<td>381.50</td>
<td>400.00</td>
<td>202.88</td>
<td>0.00</td>
<td>994836.26</td>
</tr>
<tr class="odd">
<td>2024-11-21</td>
<td>994836.26</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>228.52</td>
<td>412.87</td>
<td>244.76</td>
<td>121.93</td>
<td>155.50</td>
<td>172.75</td>
<td>146.67</td>
<td>389.59</td>
<td>410.45</td>
<td>198.38</td>
<td>0.00</td>
<td>994836.26</td>
</tr>
<tr class="even">
<td>2024-11-22</td>
<td>994836.26</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>229.87</td>
<td>417.00</td>
<td>248.55</td>
<td>121.79</td>
<td>155.17</td>
<td>176.28</td>
<td>141.95</td>
<td>397.49</td>
<td>420.00</td>
<td>197.12</td>
<td>0.00</td>
<td>994836.26</td>
</tr>
<tr class="odd">
<td>2024-11-25</td>
<td>994836.26</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>232.87</td>
<td>418.79</td>
<td>250.29</td>
<td>119.97</td>
<td>155.78</td>
<td>177.39</td>
<td>136.02</td>
<td>405.65</td>
<td>428.67</td>
<td>201.45</td>
<td>0.00</td>
<td>994836.26</td>
</tr>
<tr class="even">
<td>2024-11-26</td>
<td>994836.26</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>235.06</td>
<td>427.99</td>
<td>249.97</td>
<td>117.97</td>
<td>154.52</td>
<td>179.31</td>
<td>136.92</td>
<td>407.83</td>
<td>429.52</td>
<td>207.86</td>
<td>0.00</td>
<td>994836.26</td>
</tr>
<tr class="odd">
<td>2024-11-27</td>
<td>994836.26</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>234.93</td>
<td>422.99</td>
<td>249.79</td>
<td>117.66</td>
<td>155.40</td>
<td>179.36</td>
<td>135.34</td>
<td>403.70</td>
<td>427.19</td>
<td>205.74</td>
<td>0.00</td>
<td>994836.26</td>
</tr>
<tr class="even">
<td>2024-11-29</td>
<td>994836.26</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>237.33</td>
<td>423.46</td>
<td>249.72</td>
<td>117.96</td>
<td>155.01</td>
<td>179.26</td>
<td>138.25</td>
<td>406.11</td>
<td>429.13</td>
<td>207.89</td>
<td>0.00</td>
<td>994836.26</td>
</tr>
<tr class="odd">
<td>2024-12-02</td>
<td>1193620.09</td>
<td>-355</td>
<td>-150</td>
<td>-347</td>
<td>1694</td>
<td>-309</td>
<td>-506</td>
<td>1440</td>
<td>-206</td>
<td>-196</td>
<td>-277</td>
<td>239.59</td>
<td>430.98</td>
<td>246.25</td>
<td>117.85</td>
<td>154.80</td>
<td>179.70</td>
<td>138.63</td>
<td>402.51</td>
<td>426.96</td>
<td>210.71</td>
<td>-199614.39</td>
<td>994005.70</td>
</tr>
<tr class="even">
<td>2024-12-03</td>
<td>1193620.09</td>
<td>-355</td>
<td>-150</td>
<td>-347</td>
<td>1694</td>
<td>-309</td>
<td>-506</td>
<td>1440</td>
<td>-206</td>
<td>-196</td>
<td>-277</td>
<td>242.65</td>
<td>431.20</td>
<td>244.82</td>
<td>117.67</td>
<td>152.36</td>
<td>175.42</td>
<td>140.26</td>
<td>399.26</td>
<td>429.35</td>
<td>213.44</td>
<td>-195830.71</td>
<td>997789.38</td>
</tr>
<tr class="odd">
<td>2024-12-04</td>
<td>1193620.09</td>
<td>-355</td>
<td>-150</td>
<td>-347</td>
<td>1694</td>
<td>-309</td>
<td>-506</td>
<td>1440</td>
<td>-206</td>
<td>-196</td>
<td>-277</td>
<td>243.01</td>
<td>437.42</td>
<td>243.40</td>
<td>114.28</td>
<td>150.47</td>
<td>175.11</td>
<td>145.14</td>
<td>399.51</td>
<td>427.92</td>
<td>218.16</td>
<td>-195452.02</td>
<td>998168.07</td>
</tr>
<tr class="even">
<td>2024-12-05</td>
<td>1276017.71</td>
<td>-355</td>
<td>0</td>
<td>-347</td>
<td>1694</td>
<td>-309</td>
<td>-506</td>
<td>0</td>
<td>-206</td>
<td>-196</td>
<td>0</td>
<td>243.04</td>
<td>442.62</td>
<td>245.48</td>
<td>114.78</td>
<td>149.52</td>
<td>176.03</td>
<td>145.06</td>
<td>394.98</td>
<td>426.54</td>
<td>220.55</td>
<td>-277264.02</td>
<td>998753.69</td>
</tr>
<tr class="odd">
<td>2024-12-06</td>
<td>1276017.71</td>
<td>-355</td>
<td>0</td>
<td>-347</td>
<td>1694</td>
<td>-309</td>
<td>-506</td>
<td>0</td>
<td>-206</td>
<td>-196</td>
<td>0</td>
<td>242.84</td>
<td>443.57</td>
<td>247.36</td>
<td>113.57</td>
<td>149.31</td>
<td>173.82</td>
<td>142.44</td>
<td>395.03</td>
<td>431.37</td>
<td>227.03</td>
<td>-279668.95</td>
<td>996348.76</td>
</tr>
<tr class="even">
<td>2024-12-09</td>
<td>1276017.71</td>
<td>-355</td>
<td>0</td>
<td>-347</td>
<td>1694</td>
<td>-309</td>
<td>-506</td>
<td>0</td>
<td>-206</td>
<td>-196</td>
<td>0</td>
<td>246.75</td>
<td>446.02</td>
<td>243.81</td>
<td>112.90</td>
<td>149.60</td>
<td>170.79</td>
<td>138.81</td>
<td>399.26</td>
<td>429.18</td>
<td>226.09</td>
<td>-279958.70</td>
<td>996059.01</td>
</tr>
<tr class="odd">
<td>2024-12-10</td>
<td>1276017.71</td>
<td>-355</td>
<td>0</td>
<td>-347</td>
<td>1694</td>
<td>-309</td>
<td>-506</td>
<td>0</td>
<td>-206</td>
<td>-196</td>
<td>0</td>
<td>247.77</td>
<td>443.33</td>
<td>242.86</td>
<td>112.67</td>
<td>149.23</td>
<td>172.28</td>
<td>135.07</td>
<td>388.39</td>
<td>422.59</td>
<td>225.04</td>
<td>-277489.52</td>
<td>998528.19</td>
</tr>
<tr class="even">
<td>2024-12-11</td>
<td>1331109.11</td>
<td>0</td>
<td>0</td>
<td>-347</td>
<td>0</td>
<td>0</td>
<td>-506</td>
<td>0</td>
<td>-206</td>
<td>-196</td>
<td>0</td>
<td>246.49</td>
<td>448.99</td>
<td>243.53</td>
<td>111.92</td>
<td>146.64</td>
<td>170.63</td>
<td>139.31</td>
<td>388.87</td>
<td>421.38</td>
<td>230.26</td>
<td>-333541.39</td>
<td>997567.72</td>
</tr>
<tr class="odd">
<td>2024-12-12</td>
<td>1251749.67</td>
<td>0</td>
<td>0</td>
<td>-347</td>
<td>0</td>
<td>0</td>
<td>-506</td>
<td>0</td>
<td>0</td>
<td>-196</td>
<td>0</td>
<td>247.96</td>
<td>449.56</td>
<td>241.53</td>
<td>111.82</td>
<td>146.24</td>
<td>170.85</td>
<td>137.34</td>
<td>380.78</td>
<td>414.42</td>
<td>228.97</td>
<td>-251487.33</td>
<td>1000262.34</td>
</tr>
<tr class="even">
<td>2024-12-13</td>
<td>1251749.67</td>
<td>0</td>
<td>0</td>
<td>-347</td>
<td>0</td>
<td>0</td>
<td>-506</td>
<td>0</td>
<td>0</td>
<td>-196</td>
<td>0</td>
<td>248.13</td>
<td>447.27</td>
<td>239.94</td>
<td>110.84</td>
<td>146.62</td>
<td>171.06</td>
<td>134.25</td>
<td>380.51</td>
<td>416.98</td>
<td>227.46</td>
<td>-251543.62</td>
<td>1000206.05</td>
</tr>
<tr class="odd">
<td>2024-12-16</td>
<td>1251749.67</td>
<td>0</td>
<td>0</td>
<td>-347</td>
<td>0</td>
<td>0</td>
<td>-506</td>
<td>0</td>
<td>0</td>
<td>-196</td>
<td>0</td>
<td>251.04</td>
<td>451.59</td>
<td>239.58</td>
<td>108.47</td>
<td>143.85</td>
<td>171.14</td>
<td>132.00</td>
<td>378.92</td>
<td>410.71</td>
<td>232.93</td>
<td>-250230.26</td>
<td>1001519.41</td>
</tr>
<tr class="even">
<td>2024-12-17</td>
<td>1251749.67</td>
<td>0</td>
<td>0</td>
<td>-347</td>
<td>0</td>
<td>0</td>
<td>-506</td>
<td>0</td>
<td>0</td>
<td>-196</td>
<td>0</td>
<td>253.48</td>
<td>454.46</td>
<td>238.36</td>
<td>108.01</td>
<td>146.41</td>
<td>170.33</td>
<td>130.39</td>
<td>375.80</td>
<td>408.47</td>
<td>231.15</td>
<td>-248958.02</td>
<td>1002791.65</td>
</tr>
<tr class="odd">
<td>2024-12-18</td>
<td>1006781.59</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>248.05</td>
<td>437.39</td>
<td>230.37</td>
<td>106.42</td>
<td>144.75</td>
<td>169.08</td>
<td>128.91</td>
<td>363.89</td>
<td>393.82</td>
<td>220.52</td>
<td>0.00</td>
<td>1006781.59</td>
</tr>
<tr class="even">
<td>2024-12-19</td>
<td>1006781.59</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>249.79</td>
<td>437.03</td>
<td>232.96</td>
<td>105.51</td>
<td>143.58</td>
<td>169.19</td>
<td>130.68</td>
<td>360.37</td>
<td>385.02</td>
<td>223.29</td>
<td>0.00</td>
<td>1006781.59</td>
</tr>
<tr class="odd">
<td>2024-12-20</td>
<td>1006781.59</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>254.49</td>
<td>436.60</td>
<td>237.60</td>
<td>105.87</td>
<td>144.47</td>
<td>168.06</td>
<td>134.70</td>
<td>366.04</td>
<td>392.60</td>
<td>224.92</td>
<td>0.00</td>
<td>1006781.59</td>
</tr>
<tr class="even">
<td>2024-12-23</td>
<td>1006781.59</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>255.27</td>
<td>435.25</td>
<td>238.39</td>
<td>106.30</td>
<td>145.27</td>
<td>168.11</td>
<td>139.67</td>
<td>365.39</td>
<td>392.45</td>
<td>225.06</td>
<td>0.00</td>
<td>1006781.59</td>
</tr>
<tr class="odd">
<td>2024-12-24</td>
<td>1006781.59</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>258.20</td>
<td>439.33</td>
<td>242.31</td>
<td>106.40</td>
<td>145.85</td>
<td>168.94</td>
<td>140.22</td>
<td>367.57</td>
<td>396.14</td>
<td>229.05</td>
<td>0.00</td>
<td>1006781.59</td>
</tr>
<tr class="even">
<td>2024-12-26</td>
<td>1006781.59</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>259.02</td>
<td>438.11</td>
<td>243.14</td>
<td>106.49</td>
<td>145.58</td>
<td>170.16</td>
<td>139.93</td>
<td>367.12</td>
<td>395.14</td>
<td>227.05</td>
<td>0.00</td>
<td>1006781.59</td>
</tr>
<tr class="odd">
<td>2024-12-27</td>
<td>1006781.59</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>255.59</td>
<td>430.53</td>
<td>241.17</td>
<td>106.48</td>
<td>145.05</td>
<td>169.53</td>
<td>137.01</td>
<td>364.86</td>
<td>392.86</td>
<td>223.75</td>
<td>0.00</td>
<td>1006781.59</td>
</tr>
<tr class="even">
<td>2024-12-30</td>
<td>1006781.59</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>252.20</td>
<td>424.83</td>
<td>239.32</td>
<td>105.76</td>
<td>143.34</td>
<td>167.09</td>
<td>137.49</td>
<td>363.01</td>
<td>389.43</td>
<td>221.30</td>
<td>0.00</td>
<td>1006781.59</td>
</tr>
<tr class="odd">
<td>2024-12-31</td>
<td>1006781.59</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>250.42</td>
<td>421.50</td>
<td>239.71</td>
<td>107.57</td>
<td>144.62</td>
<td>167.65</td>
<td>134.29</td>
<td>362.76</td>
<td>388.99</td>
<td>219.39</td>
<td>0.00</td>
<td>1006781.59</td>
</tr>
<tr class="even">
<td>2025-01-02</td>
<td>371564.07</td>
<td>-730</td>
<td>246</td>
<td>342</td>
<td>836</td>
<td>456</td>
<td>490</td>
<td>760</td>
<td>287</td>
<td>243</td>
<td>392</td>
<td>243.85</td>
<td>418.58</td>
<td>240.00</td>
<td>107.31</td>
<td>144.02</td>
<td>165.98</td>
<td>138.31</td>
<td>359.77</td>
<td>388.46</td>
<td>220.22</td>
<td>632846.27</td>
<td>1004410.34</td>
</tr>
<tr class="odd">
<td>2025-01-03</td>
<td>480950.87</td>
<td>-730</td>
<td>246</td>
<td>342</td>
<td>836</td>
<td>456</td>
<td>490</td>
<td>0</td>
<td>287</td>
<td>243</td>
<td>392</td>
<td>243.36</td>
<td>423.35</td>
<td>243.28</td>
<td>107.86</td>
<td>144.19</td>
<td>165.13</td>
<td>144.47</td>
<td>363.79</td>
<td>389.18</td>
<td>224.19</td>
<td>533389.31</td>
<td>1014340.18</td>
</tr>
<tr class="even">
<td>2025-01-06</td>
<td>480950.87</td>
<td>-730</td>
<td>246</td>
<td>342</td>
<td>836</td>
<td>456</td>
<td>490</td>
<td>0</td>
<td>287</td>
<td>243</td>
<td>392</td>
<td>245.00</td>
<td>427.85</td>
<td>240.85</td>
<td>107.74</td>
<td>143.66</td>
<td>160.60</td>
<td>149.43</td>
<td>364.20</td>
<td>389.37</td>
<td>227.61</td>
<td>531410.83</td>
<td>1012361.70</td>
</tr>
<tr class="odd">
<td>2025-01-07</td>
<td>480950.87</td>
<td>-730</td>
<td>246</td>
<td>342</td>
<td>836</td>
<td>456</td>
<td>490</td>
<td>0</td>
<td>287</td>
<td>243</td>
<td>392</td>
<td>242.21</td>
<td>422.37</td>
<td>243.17</td>
<td>108.75</td>
<td>146.23</td>
<td>161.30</td>
<td>140.14</td>
<td>363.00</td>
<td>384.23</td>
<td>222.11</td>
<td>531502.75</td>
<td>1012453.62</td>
</tr>
<tr class="even">
<td>2025-01-08</td>
<td>480950.87</td>
<td>-730</td>
<td>246</td>
<td>342</td>
<td>836</td>
<td>456</td>
<td>490</td>
<td>0</td>
<td>287</td>
<td>243</td>
<td>392</td>
<td>242.70</td>
<td>424.56</td>
<td>243.13</td>
<td>106.93</td>
<td>142.27</td>
<td>162.10</td>
<td>140.11</td>
<td>361.07</td>
<td>387.20</td>
<td>222.13</td>
<td>528910.47</td>
<td>1009861.34</td>
</tr>
<tr class="odd">
<td>2025-01-10</td>
<td>386798.27</td>
<td>0</td>
<td>246</td>
<td>342</td>
<td>836</td>
<td>456</td>
<td>0</td>
<td>0</td>
<td>287</td>
<td>243</td>
<td>392</td>
<td>236.85</td>
<td>418.95</td>
<td>239.87</td>
<td>106.54</td>
<td>142.06</td>
<td>158.56</td>
<td>135.91</td>
<td>351.00</td>
<td>389.89</td>
<td>218.94</td>
<td>620248.79</td>
<td>1007047.06</td>
</tr>
<tr class="even">
<td>2025-01-13</td>
<td>386798.27</td>
<td>0</td>
<td>246</td>
<td>342</td>
<td>836</td>
<td>456</td>
<td>0</td>
<td>0</td>
<td>287</td>
<td>243</td>
<td>392</td>
<td>234.40</td>
<td>417.19</td>
<td>244.21</td>
<td>109.29</td>
<td>144.47</td>
<td>158.84</td>
<td>133.23</td>
<td>362.50</td>
<td>389.18</td>
<td>218.46</td>
<td>627637.88</td>
<td>1014436.15</td>
</tr>
<tr class="odd">
<td>2025-01-14</td>
<td>386798.27</td>
<td>0</td>
<td>246</td>
<td>342</td>
<td>836</td>
<td>456</td>
<td>0</td>
<td>0</td>
<td>287</td>
<td>243</td>
<td>392</td>
<td>233.28</td>
<td>415.67</td>
<td>247.47</td>
<td>109.72</td>
<td>144.75</td>
<td>159.74</td>
<td>131.76</td>
<td>371.57</td>
<td>392.78</td>
<td>217.76</td>
<td>632069.53</td>
<td>1018867.80</td>
</tr>
<tr class="even">
<td>2025-01-15</td>
<td>386798.27</td>
<td>0</td>
<td>246</td>
<td>342</td>
<td>836</td>
<td>456</td>
<td>0</td>
<td>0</td>
<td>287</td>
<td>243</td>
<td>392</td>
<td>237.87</td>
<td>426.31</td>
<td>252.35</td>
<td>111.51</td>
<td>144.97</td>
<td>159.65</td>
<td>136.24</td>
<td>374.89</td>
<td>406.09</td>
<td>223.35</td>
<td>644331.14</td>
<td>1031129.41</td>
</tr>
<tr class="odd">
<td>2025-01-16</td>
<td>474353.69</td>
<td>0</td>
<td>246</td>
<td>0</td>
<td>836</td>
<td>456</td>
<td>0</td>
<td>0</td>
<td>287</td>
<td>243</td>
<td>392</td>
<td>228.26</td>
<td>424.58</td>
<td>254.27</td>
<td>111.32</td>
<td>147.77</td>
<td>160.50</td>
<td>133.57</td>
<td>380.55</td>
<td>409.33</td>
<td>220.66</td>
<td>560077.08</td>
<td>1034430.77</td>
</tr>
<tr class="even">
<td>2025-01-17</td>
<td>585239.01</td>
<td>0</td>
<td>246</td>
<td>0</td>
<td>836</td>
<td>456</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>243</td>
<td>392</td>
<td>229.98</td>
<td>429.03</td>
<td>259.16</td>
<td>112.32</td>
<td>147.03</td>
<td>161.13</td>
<td>137.71</td>
<td>386.02</td>
<td>409.38</td>
<td>225.94</td>
<td>454534.40</td>
<td>1039773.41</td>
</tr>
<tr class="odd">
<td>2025-01-21</td>
<td>686438.79</td>
<td>0</td>
<td>246</td>
<td>0</td>
<td>836</td>
<td>456</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>392</td>
<td>222.64</td>
<td>428.50</td>
<td>263.03</td>
<td>111.47</td>
<td>148.15</td>
<td>161.72</td>
<td>140.83</td>
<td>398.36</td>
<td>418.43</td>
<td>230.71</td>
<td>356594.64</td>
<td>1043033.43</td>
</tr>
<tr class="even">
<td>2025-01-22</td>
<td>778586.23</td>
<td>0</td>
<td>246</td>
<td>0</td>
<td>836</td>
<td>456</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>223.83</td>
<td>446.20</td>
<td>262.84</td>
<td>109.53</td>
<td>145.27</td>
<td>164.74</td>
<td>147.07</td>
<td>397.61</td>
<td>410.10</td>
<td>235.01</td>
<td>267575.40</td>
<td>1046161.63</td>
</tr>
<tr class="odd">
<td>2025-01-23</td>
<td>778586.23</td>
<td>0</td>
<td>246</td>
<td>0</td>
<td>836</td>
<td>456</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>223.66</td>
<td>446.71</td>
<td>265.95</td>
<td>110.15</td>
<td>146.64</td>
<td>166.15</td>
<td>147.22</td>
<td>406.40</td>
<td>414.39</td>
<td>235.42</td>
<td>268843.90</td>
<td>1047430.13</td>
</tr>
<tr class="even">
<td>2025-01-24</td>
<td>778586.23</td>
<td>0</td>
<td>246</td>
<td>0</td>
<td>836</td>
<td>456</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>222.78</td>
<td>444.06</td>
<td>264.84</td>
<td>108.66</td>
<td>146.82</td>
<td>164.12</td>
<td>142.62</td>
<td>407.63</td>
<td>414.50</td>
<td>234.85</td>
<td>267028.44</td>
<td>1045614.67</td>
</tr>
<tr class="odd">
<td>2025-01-27</td>
<td>778586.23</td>
<td>0</td>
<td>246</td>
<td>0</td>
<td>836</td>
<td>456</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>229.86</td>
<td>434.56</td>
<td>265.85</td>
<td>110.17</td>
<td>152.89</td>
<td>169.66</td>
<td>118.42</td>
<td>394.98</td>
<td>424.87</td>
<td>235.42</td>
<td>268721.72</td>
<td>1047307.95</td>
</tr>
<tr class="even">
<td>2025-01-28</td>
<td>778586.23</td>
<td>0</td>
<td>246</td>
<td>0</td>
<td>836</td>
<td>456</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>238.26</td>
<td>447.20</td>
<td>267.14</td>
<td>108.04</td>
<td>150.38</td>
<td>166.19</td>
<td>128.99</td>
<td>390.29</td>
<td>418.83</td>
<td>238.15</td>
<td>268905.92</td>
<td>1047492.15</td>
</tr>
<tr class="odd">
<td>2025-01-29</td>
<td>778586.23</td>
<td>0</td>
<td>246</td>
<td>0</td>
<td>836</td>
<td>456</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>239.36</td>
<td>442.33</td>
<td>266.58</td>
<td>108.67</td>
<td>151.15</td>
<td>166.23</td>
<td>123.70</td>
<td>393.23</td>
<td>413.42</td>
<td>237.07</td>
<td>268585.70</td>
<td>1047171.93</td>
</tr>
<tr class="even">
<td>2025-01-30</td>
<td>848814.79</td>
<td>0</td>
<td>246</td>
<td>0</td>
<td>836</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>237.59</td>
<td>414.99</td>
<td>268.23</td>
<td>109.57</td>
<td>152.87</td>
<td>167.41</td>
<td>124.65</td>
<td>374.98</td>
<td>414.50</td>
<td>234.64</td>
<td>193688.06</td>
<td>1042502.85</td>
</tr>
<tr class="odd">
<td>2025-01-31</td>
<td>1040229.43</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>236.00</td>
<td>415.06</td>
<td>267.30</td>
<td>106.83</td>
<td>152.15</td>
<td>165.99</td>
<td>120.07</td>
<td>371.44</td>
<td>411.98</td>
<td>237.68</td>
<td>0.00</td>
<td>1040229.43</td>
</tr>
<tr class="even">
<td>2025-02-03</td>
<td>1039692.54</td>
<td>724</td>
<td>404</td>
<td>-336</td>
<td>-505</td>
<td>-519</td>
<td>-365</td>
<td>1452</td>
<td>-169</td>
<td>-178</td>
<td>-359</td>
<td>228.01</td>
<td>410.92</td>
<td>266.81</td>
<td>107.09</td>
<td>151.87</td>
<td>168.76</td>
<td>116.66</td>
<td>361.55</td>
<td>408.76</td>
<td>237.42</td>
<td>-2760.31</td>
<td>1036932.23</td>
</tr>
<tr class="odd">
<td>2025-02-04</td>
<td>1039692.54</td>
<td>724</td>
<td>404</td>
<td>-336</td>
<td>-505</td>
<td>-519</td>
<td>-365</td>
<td>1452</td>
<td>-169</td>
<td>-178</td>
<td>-359</td>
<td>232.80</td>
<td>412.37</td>
<td>267.94</td>
<td>109.96</td>
<td>153.49</td>
<td>168.13</td>
<td>118.65</td>
<td>361.95</td>
<td>411.49</td>
<td>242.06</td>
<td>-476.23</td>
<td>1039216.31</td>
</tr>
<tr class="even">
<td>2025-02-05</td>
<td>1219813.14</td>
<td>724</td>
<td>404</td>
<td>-336</td>
<td>-505</td>
<td>-519</td>
<td>-365</td>
<td>0</td>
<td>-169</td>
<td>-178</td>
<td>-359</td>
<td>232.47</td>
<td>413.29</td>
<td>270.43</td>
<td>109.88</td>
<td>154.69</td>
<td>169.01</td>
<td>124.83</td>
<td>358.85</td>
<td>413.82</td>
<td>236.17</td>
<td>-172139.84</td>
<td>1047673.30</td>
</tr>
<tr class="odd">
<td>2025-02-06</td>
<td>1219813.14</td>
<td>724</td>
<td>404</td>
<td>-336</td>
<td>-505</td>
<td>-519</td>
<td>-365</td>
<td>0</td>
<td>-169</td>
<td>-178</td>
<td>-359</td>
<td>233.22</td>
<td>415.82</td>
<td>276.90</td>
<td>108.43</td>
<td>153.51</td>
<td>168.88</td>
<td>128.68</td>
<td>365.45</td>
<td>414.16</td>
<td>238.83</td>
<td>-173487.38</td>
<td>1046325.76</td>
</tr>
<tr class="even">
<td>2025-02-07</td>
<td>1219813.14</td>
<td>724</td>
<td>404</td>
<td>-336</td>
<td>-505</td>
<td>-519</td>
<td>-365</td>
<td>0</td>
<td>-169</td>
<td>-178</td>
<td>-359</td>
<td>227.63</td>
<td>409.75</td>
<td>275.80</td>
<td>108.89</td>
<td>153.12</td>
<td>167.97</td>
<td>129.84</td>
<td>363.88</td>
<td>407.37</td>
<td>229.15</td>
<td>-174365.89</td>
<td>1045447.25</td>
</tr>
<tr class="odd">
<td>2025-02-10</td>
<td>1219813.14</td>
<td>724</td>
<td>404</td>
<td>-336</td>
<td>-505</td>
<td>-519</td>
<td>-365</td>
<td>0</td>
<td>-169</td>
<td>-178</td>
<td>-359</td>
<td>227.65</td>
<td>412.22</td>
<td>271.04</td>
<td>110.97</td>
<td>154.24</td>
<td>167.53</td>
<td>133.57</td>
<td>363.22</td>
<td>413.99</td>
<td>233.14</td>
<td>-175724.48</td>
<td>1044088.66</td>
</tr>
<tr class="even">
<td>2025-02-11</td>
<td>1219813.14</td>
<td>724</td>
<td>404</td>
<td>-336</td>
<td>-505</td>
<td>-519</td>
<td>-365</td>
<td>0</td>
<td>-169</td>
<td>-178</td>
<td>-359</td>
<td>232.62</td>
<td>411.44</td>
<td>274.99</td>
<td>111.67</td>
<td>156.13</td>
<td>169.43</td>
<td>132.80</td>
<td>362.23</td>
<td>416.36</td>
<td>232.76</td>
<td>-175914.56</td>
<td>1043898.58</td>
</tr>
<tr class="odd">
<td>2025-02-12</td>
<td>1219813.14</td>
<td>724</td>
<td>404</td>
<td>-336</td>
<td>-505</td>
<td>-519</td>
<td>-365</td>
<td>0</td>
<td>-169</td>
<td>-178</td>
<td>-359</td>
<td>236.87</td>
<td>409.04</td>
<td>275.45</td>
<td>107.35</td>
<td>155.26</td>
<td>169.58</td>
<td>131.14</td>
<td>352.04</td>
<td>407.14</td>
<td>228.93</td>
<td>-166645.10</td>
<td>1053168.04</td>
</tr>
<tr class="even">
<td>2025-02-13</td>
<td>1219813.14</td>
<td>724</td>
<td>404</td>
<td>-336</td>
<td>-505</td>
<td>-519</td>
<td>-365</td>
<td>0</td>
<td>-169</td>
<td>-178</td>
<td>-359</td>
<td>241.53</td>
<td>410.54</td>
<td>276.32</td>
<td>108.13</td>
<td>157.25</td>
<td>171.02</td>
<td>135.29</td>
<td>353.70</td>
<td>412.43</td>
<td>230.37</td>
<td>-166649.01</td>
<td>1053164.13</td>
</tr>
<tr class="odd">
<td>2025-02-14</td>
<td>1219813.14</td>
<td>724</td>
<td>404</td>
<td>-336</td>
<td>-505</td>
<td>-519</td>
<td>-365</td>
<td>0</td>
<td>-169</td>
<td>-178</td>
<td>-359</td>
<td>244.60</td>
<td>408.43</td>
<td>276.59</td>
<td>108.24</td>
<td>156.15</td>
<td>162.89</td>
<td>138.85</td>
<td>353.32</td>
<td>409.50</td>
<td>228.68</td>
<td>-160694.22</td>
<td>1059118.92</td>
</tr>
<tr class="even">
<td>2025-02-18</td>
<td>1219813.14</td>
<td>724</td>
<td>404</td>
<td>-336</td>
<td>-505</td>
<td>-519</td>
<td>-365</td>
<td>0</td>
<td>-169</td>
<td>-178</td>
<td>-359</td>
<td>244.47</td>
<td>409.64</td>
<td>279.95</td>
<td>110.14</td>
<td>154.99</td>
<td>165.43</td>
<td>139.40</td>
<td>354.00</td>
<td>403.31</td>
<td>226.65</td>
<td>-160997.35</td>
<td>1058815.79</td>
</tr>
<tr class="odd">
<td>2025-02-19</td>
<td>1219813.14</td>
<td>724</td>
<td>404</td>
<td>-336</td>
<td>-505</td>
<td>-519</td>
<td>-365</td>
<td>0</td>
<td>-169</td>
<td>-178</td>
<td>-359</td>
<td>244.87</td>
<td>414.77</td>
<td>279.25</td>
<td>110.30</td>
<td>157.89</td>
<td>166.49</td>
<td>139.23</td>
<td>353.00</td>
<td>395.43</td>
<td>226.63</td>
<td>-158794.01</td>
<td>1061019.13</td>
</tr>
<tr class="even">
<td>2025-02-20</td>
<td>1219813.14</td>
<td>724</td>
<td>404</td>
<td>-336</td>
<td>-505</td>
<td>-519</td>
<td>-365</td>
<td>0</td>
<td>-169</td>
<td>-178</td>
<td>-359</td>
<td>245.83</td>
<td>416.13</td>
<td>266.80</td>
<td>112.00</td>
<td>159.68</td>
<td>167.21</td>
<td>140.11</td>
<td>349.15</td>
<td>394.64</td>
<td>222.88</td>
<td>-153279.12</td>
<td>1066534.02</td>
</tr>
<tr class="odd">
<td>2025-02-21</td>
<td>1236467.44</td>
<td>0</td>
<td>404</td>
<td>-336</td>
<td>-505</td>
<td>0</td>
<td>-365</td>
<td>0</td>
<td>-169</td>
<td>-178</td>
<td>0</td>
<td>245.55</td>
<td>408.21</td>
<td>264.24</td>
<td>110.69</td>
<td>162.30</td>
<td>170.23</td>
<td>134.43</td>
<td>340.04</td>
<td>385.30</td>
<td>216.58</td>
<td>-167950.36</td>
<td>1068517.08</td>
</tr>
<tr class="even">
<td>2025-02-24</td>
<td>1236467.44</td>
<td>0</td>
<td>404</td>
<td>-336</td>
<td>-505</td>
<td>0</td>
<td>-365</td>
<td>0</td>
<td>-169</td>
<td>-178</td>
<td>0</td>
<td>247.10</td>
<td>404.00</td>
<td>261.34</td>
<td>111.27</td>
<td>163.74</td>
<td>170.54</td>
<td>130.28</td>
<td>338.92</td>
<td>382.42</td>
<td>212.71</td>
<td>-168380.93</td>
<td>1068086.51</td>
</tr>
<tr class="odd">
<td>2025-02-25</td>
<td>1236467.44</td>
<td>0</td>
<td>404</td>
<td>-336</td>
<td>-505</td>
<td>0</td>
<td>-365</td>
<td>0</td>
<td>-169</td>
<td>-178</td>
<td>0</td>
<td>247.04</td>
<td>397.90</td>
<td>257.40</td>
<td>109.73</td>
<td>166.09</td>
<td>172.65</td>
<td>126.63</td>
<td>342.36</td>
<td>393.29</td>
<td>212.80</td>
<td>-172030.16</td>
<td>1064437.28</td>
</tr>
<tr class="even">
<td>2025-02-26</td>
<td>1236467.44</td>
<td>0</td>
<td>404</td>
<td>-336</td>
<td>-505</td>
<td>0</td>
<td>-365</td>
<td>0</td>
<td>-169</td>
<td>-178</td>
<td>0</td>
<td>240.36</td>
<td>399.73</td>
<td>258.79</td>
<td>109.46</td>
<td>163.08</td>
<td>171.30</td>
<td>131.28</td>
<td>342.58</td>
<td>390.48</td>
<td>214.35</td>
<td>-170665.78</td>
<td>1065801.66</td>
</tr>
<tr class="odd">
<td>2025-02-27</td>
<td>1236467.44</td>
<td>0</td>
<td>404</td>
<td>-336</td>
<td>-505</td>
<td>0</td>
<td>-365</td>
<td>0</td>
<td>-169</td>
<td>-178</td>
<td>0</td>
<td>237.30</td>
<td>392.53</td>
<td>259.05</td>
<td>110.15</td>
<td>163.73</td>
<td>171.97</td>
<td>120.15</td>
<td>340.00</td>
<td>390.27</td>
<td>208.74</td>
<td>-173781.54</td>
<td>1062685.90</td>
</tr>
<tr class="even">
<td>2025-02-28</td>
<td>1059533.40</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>241.84</td>
<td>396.99</td>
<td>264.65</td>
<td>111.33</td>
<td>165.02</td>
<td>173.84</td>
<td>124.92</td>
<td>343.95</td>
<td>396.60</td>
<td>212.28</td>
<td>0.00</td>
<td>1059533.40</td>
</tr>
<tr class="odd">
<td>2025-03-03</td>
<td>859900.13</td>
<td>-404</td>
<td>255</td>
<td>345</td>
<td>-706</td>
<td>-634</td>
<td>-682</td>
<td>852</td>
<td>272</td>
<td>260</td>
<td>485</td>
<td>238.03</td>
<td>388.49</td>
<td>260.62</td>
<td>107.76</td>
<td>167.28</td>
<td>175.59</td>
<td>114.06</td>
<td>332.04</td>
<td>389.69</td>
<td>205.02</td>
<td>179176.37</td>
<td>1039076.50</td>
</tr>
<tr class="even">
<td>2025-03-04</td>
<td>859900.13</td>
<td>-404</td>
<td>255</td>
<td>345</td>
<td>-706</td>
<td>-634</td>
<td>-682</td>
<td>852</td>
<td>272</td>
<td>260</td>
<td>485</td>
<td>235.93</td>
<td>388.61</td>
<td>250.25</td>
<td>107.54</td>
<td>165.42</td>
<td>173.18</td>
<td>115.99</td>
<td>326.75</td>
<td>381.68</td>
<td>203.80</td>
<td>176987.08</td>
<td>1036887.21</td>
</tr>
<tr class="odd">
<td>2025-03-05</td>
<td>859900.13</td>
<td>-404</td>
<td>255</td>
<td>345</td>
<td>-706</td>
<td>-634</td>
<td>-682</td>
<td>852</td>
<td>272</td>
<td>260</td>
<td>485</td>
<td>235.74</td>
<td>401.02</td>
<td>251.53</td>
<td>105.44</td>
<td>165.12</td>
<td>174.61</td>
<td>117.30</td>
<td>338.49</td>
<td>386.35</td>
<td>208.36</td>
<td>189102.73</td>
<td>1049002.86</td>
</tr>
<tr class="even">
<td>2025-03-06</td>
<td>954335.81</td>
<td>-404</td>
<td>255</td>
<td>345</td>
<td>-706</td>
<td>-634</td>
<td>-682</td>
<td>0</td>
<td>272</td>
<td>260</td>
<td>485</td>
<td>235.33</td>
<td>396.89</td>
<td>246.54</td>
<td>107.62</td>
<td>165.83</td>
<td>174.66</td>
<td>110.57</td>
<td>341.01</td>
<td>381.73</td>
<td>200.70</td>
<td>80299.89</td>
<td>1034635.70</td>
</tr>
<tr class="odd">
<td>2025-03-07</td>
<td>954335.81</td>
<td>-404</td>
<td>255</td>
<td>345</td>
<td>-706</td>
<td>-634</td>
<td>-682</td>
<td>0</td>
<td>272</td>
<td>260</td>
<td>485</td>
<td>239.07</td>
<td>393.31</td>
<td>242.28</td>
<td>109.02</td>
<td>166.69</td>
<td>175.95</td>
<td>112.69</td>
<td>350.30</td>
<td>376.80</td>
<td>199.25</td>
<td>74534.74</td>
<td>1028870.55</td>
</tr>
<tr class="even">
<td>2025-03-10</td>
<td>1128072.21</td>
<td>-404</td>
<td>255</td>
<td>0</td>
<td>-706</td>
<td>-634</td>
<td>-682</td>
<td>0</td>
<td>272</td>
<td>260</td>
<td>0</td>
<td>227.48</td>
<td>380.16</td>
<td>232.22</td>
<td>111.80</td>
<td>167.70</td>
<td>176.26</td>
<td>106.98</td>
<td>345.21</td>
<td>374.65</td>
<td>194.54</td>
<td>-109116.92</td>
<td>1018955.29</td>
</tr>
<tr class="odd">
<td>2025-03-11</td>
<td>1128072.21</td>
<td>-404</td>
<td>255</td>
<td>0</td>
<td>-706</td>
<td>-634</td>
<td>-682</td>
<td>0</td>
<td>272</td>
<td>260</td>
<td>0</td>
<td>220.84</td>
<td>380.45</td>
<td>229.14</td>
<td>109.16</td>
<td>165.86</td>
<td>173.12</td>
<td>108.76</td>
<td>339.77</td>
<td>368.16</td>
<td>196.59</td>
<td>-104355.61</td>
<td>1023716.60</td>
</tr>
<tr class="even">
<td>2025-03-12</td>
<td>1040767.81</td>
<td>0</td>
<td>255</td>
<td>0</td>
<td>-706</td>
<td>-634</td>
<td>-682</td>
<td>0</td>
<td>272</td>
<td>260</td>
<td>0</td>
<td>216.98</td>
<td>383.27</td>
<td>227.90</td>
<td>109.13</td>
<td>162.85</td>
<td>168.37</td>
<td>115.74</td>
<td>338.13</td>
<td>364.73</td>
<td>198.89</td>
<td>-10586.01</td>
<td>1030181.80</td>
</tr>
<tr class="odd">
<td>2025-03-13</td>
<td>1133013.21</td>
<td>0</td>
<td>255</td>
<td>0</td>
<td>-706</td>
<td>-634</td>
<td>-682</td>
<td>0</td>
<td>272</td>
<td>0</td>
<td>0</td>
<td>209.68</td>
<td>378.77</td>
<td>225.19</td>
<td>108.67</td>
<td>162.99</td>
<td>168.59</td>
<td>115.58</td>
<td>333.31</td>
<td>347.25</td>
<td>193.89</td>
<td>-107788.39</td>
<td>1025224.82</td>
</tr>
<tr class="even">
<td>2025-03-14</td>
<td>1133013.21</td>
<td>0</td>
<td>255</td>
<td>0</td>
<td>-706</td>
<td>-634</td>
<td>-682</td>
<td>0</td>
<td>272</td>
<td>0</td>
<td>0</td>
<td>213.49</td>
<td>388.56</td>
<td>232.44</td>
<td>111.90</td>
<td>162.81</td>
<td>167.97</td>
<td>121.67</td>
<td>339.64</td>
<td>351.31</td>
<td>197.95</td>
<td>-105313.60</td>
<td>1027699.61</td>
</tr>
<tr class="odd">
<td>2025-03-17</td>
<td>1133013.21</td>
<td>0</td>
<td>255</td>
<td>0</td>
<td>-706</td>
<td>-634</td>
<td>-682</td>
<td>0</td>
<td>272</td>
<td>0</td>
<td>0</td>
<td>214.00</td>
<td>388.70</td>
<td>233.93</td>
<td>113.76</td>
<td>162.84</td>
<td>169.76</td>
<td>119.53</td>
<td>342.64</td>
<td>354.13</td>
<td>195.74</td>
<td>-107014.86</td>
<td>1025998.35</td>
</tr>
<tr class="even">
<td>2025-03-18</td>
<td>1133013.21</td>
<td>0</td>
<td>255</td>
<td>0</td>
<td>-706</td>
<td>-634</td>
<td>-682</td>
<td>0</td>
<td>272</td>
<td>0</td>
<td>0</td>
<td>212.69</td>
<td>383.52</td>
<td>234.97</td>
<td>113.64</td>
<td>164.25</td>
<td>167.71</td>
<td>115.43</td>
<td>336.71</td>
<td>349.57</td>
<td>192.82</td>
<td>-109359.84</td>
<td>1023653.37</td>
</tr>
<tr class="odd">
<td>2025-03-19</td>
<td>1133013.21</td>
<td>0</td>
<td>255</td>
<td>0</td>
<td>-706</td>
<td>-634</td>
<td>-682</td>
<td>0</td>
<td>272</td>
<td>0</td>
<td>0</td>
<td>215.24</td>
<td>387.82</td>
<td>239.11</td>
<td>115.41</td>
<td>162.99</td>
<td>168.57</td>
<td>117.52</td>
<td>338.62</td>
<td>353.42</td>
<td>195.54</td>
<td>-108781.12</td>
<td>1024232.09</td>
</tr>
<tr class="even">
<td>2025-03-20</td>
<td>1133013.21</td>
<td>0</td>
<td>255</td>
<td>0</td>
<td>-706</td>
<td>-634</td>
<td>-682</td>
<td>0</td>
<td>272</td>
<td>0</td>
<td>0</td>
<td>214.10</td>
<td>386.84</td>
<td>239.01</td>
<td>115.90</td>
<td>163.02</td>
<td>167.55</td>
<td>118.53</td>
<td>336.25</td>
<td>355.52</td>
<td>194.95</td>
<td>-109344.98</td>
<td>1023668.23</td>
</tr>
<tr class="odd">
<td>2025-03-21</td>
<td>1133013.21</td>
<td>0</td>
<td>255</td>
<td>0</td>
<td>-706</td>
<td>-634</td>
<td>-682</td>
<td>0</td>
<td>272</td>
<td>0</td>
<td>0</td>
<td>218.27</td>
<td>391.26</td>
<td>241.63</td>
<td>115.50</td>
<td>163.63</td>
<td>166.69</td>
<td>117.70</td>
<td>335.78</td>
<td>351.15</td>
<td>196.21</td>
<td>-107863.54</td>
<td>1025149.67</td>
</tr>
<tr class="even">
<td>2025-03-24</td>
<td>1133013.21</td>
<td>0</td>
<td>255</td>
<td>0</td>
<td>-706</td>
<td>-634</td>
<td>-682</td>
<td>0</td>
<td>272</td>
<td>0</td>
<td>0</td>
<td>220.73</td>
<td>393.08</td>
<td>248.06</td>
<td>115.80</td>
<td>163.29</td>
<td>165.65</td>
<td>121.41</td>
<td>341.67</td>
<td>363.77</td>
<td>203.26</td>
<td>-105084.32</td>
<td>1027928.89</td>
</tr>
<tr class="odd">
<td>2025-03-25</td>
<td>1133013.21</td>
<td>0</td>
<td>255</td>
<td>0</td>
<td>-706</td>
<td>-634</td>
<td>-682</td>
<td>0</td>
<td>272</td>
<td>0</td>
<td>0</td>
<td>223.75</td>
<td>395.16</td>
<td>251.13</td>
<td>116.59</td>
<td>161.02</td>
<td>162.85</td>
<td>120.69</td>
<td>342.62</td>
<td>360.99</td>
<td>205.71</td>
<td>-101504.48</td>
<td>1031508.73</td>
</tr>
<tr class="even">
<td>2025-03-26</td>
<td>1133013.21</td>
<td>0</td>
<td>255</td>
<td>0</td>
<td>-706</td>
<td>-634</td>
<td>-682</td>
<td>0</td>
<td>272</td>
<td>0</td>
<td>0</td>
<td>221.53</td>
<td>389.97</td>
<td>251.03</td>
<td>118.27</td>
<td>161.72</td>
<td>166.58</td>
<td>113.76</td>
<td>341.11</td>
<td>362.13</td>
<td>201.13</td>
<td>-107412.39</td>
<td>1025600.82</td>
</tr>
<tr class="odd">
<td>2025-03-27</td>
<td>1133013.21</td>
<td>0</td>
<td>255</td>
<td>0</td>
<td>-706</td>
<td>-634</td>
<td>-682</td>
<td>0</td>
<td>272</td>
<td>0</td>
<td>0</td>
<td>223.85</td>
<td>390.58</td>
<td>248.12</td>
<td>117.89</td>
<td>163.13</td>
<td>168.71</td>
<td>111.43</td>
<td>339.30</td>
<td>362.73</td>
<td>201.36</td>
<td>-109827.48</td>
<td>1023185.73</td>
</tr>
<tr class="even">
<td>2025-03-28</td>
<td>1133013.21</td>
<td>0</td>
<td>255</td>
<td>0</td>
<td>-706</td>
<td>-634</td>
<td>-682</td>
<td>0</td>
<td>272</td>
<td>0</td>
<td>0</td>
<td>217.90</td>
<td>378.80</td>
<td>242.85</td>
<td>117.73</td>
<td>163.71</td>
<td>168.03</td>
<td>109.67</td>
<td>329.69</td>
<td>358.15</td>
<td>192.72</td>
<td>-115236.30</td>
<td>1017776.91</td>
</tr>
<tr class="odd">
<td>2025-03-31</td>
<td>1013109.68</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>222.13</td>
<td>375.39</td>
<td>245.30</td>
<td>118.93</td>
<td>165.84</td>
<td>170.42</td>
<td>108.38</td>
<td>329.80</td>
<td>366.49</td>
<td>190.26</td>
<td>0.00</td>
<td>1013109.68</td>
</tr>
<tr class="even">
<td>2025-04-01</td>
<td>741237.97</td>
<td>401</td>
<td>221</td>
<td>-371</td>
<td>-1185</td>
<td>439</td>
<td>476</td>
<td>1074</td>
<td>-404</td>
<td>189</td>
<td>677</td>
<td>223.19</td>
<td>382.19</td>
<td>243.66</td>
<td>119.04</td>
<td>153.25</td>
<td>170.56</td>
<td>110.15</td>
<td>330.57</td>
<td>365.52</td>
<td>192.17</td>
<td>274899.42</td>
<td>1016137.39</td>
</tr>
<tr class="odd">
<td>2025-04-02</td>
<td>874688.21</td>
<td>401</td>
<td>221</td>
<td>-371</td>
<td>-1185</td>
<td>439</td>
<td>476</td>
<td>1074</td>
<td>-404</td>
<td>189</td>
<td>0</td>
<td>223.89</td>
<td>382.14</td>
<td>245.82</td>
<td>118.67</td>
<td>155.36</td>
<td>169.50</td>
<td>110.42</td>
<td>334.66</td>
<td>370.89</td>
<td>196.01</td>
<td>144781.35</td>
<td>1019469.56</td>
</tr>
<tr class="even">
<td>2025-04-03</td>
<td>723552.74</td>
<td>0</td>
<td>221</td>
<td>0</td>
<td>0</td>
<td>439</td>
<td>476</td>
<td>0</td>
<td>0</td>
<td>189</td>
<td>0</td>
<td>203.19</td>
<td>373.11</td>
<td>228.69</td>
<td>112.43</td>
<td>159.82</td>
<td>172.39</td>
<td>101.80</td>
<td>305.76</td>
<td>355.91</td>
<td>178.41</td>
<td>301942.92</td>
<td>1025495.66</td>
</tr>
<tr class="odd">
<td>2025-04-04</td>
<td>723552.74</td>
<td>0</td>
<td>221</td>
<td>0</td>
<td>0</td>
<td>439</td>
<td>476</td>
<td>0</td>
<td>0</td>
<td>189</td>
<td>0</td>
<td>188.38</td>
<td>359.84</td>
<td>210.28</td>
<td>104.34</td>
<td>153.24</td>
<td>163.75</td>
<td>94.31</td>
<td>288.08</td>
<td>353.90</td>
<td>171.00</td>
<td>291629.10</td>
<td>1015181.84</td>
</tr>
<tr class="even">
<td>2025-04-07</td>
<td>1007410.80</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>181.46</td>
<td>357.86</td>
<td>214.44</td>
<td>102.94</td>
<td>150.62</td>
<td>160.23</td>
<td>97.64</td>
<td>280.06</td>
<td>341.51</td>
<td>175.26</td>
<td>0.00</td>
<td>1007410.80</td>
</tr>
<tr class="odd">
<td>2025-04-08</td>
<td>1007410.80</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>172.42</td>
<td>354.56</td>
<td>216.87</td>
<td>100.77</td>
<td>150.00</td>
<td>158.39</td>
<td>96.30</td>
<td>273.94</td>
<td>335.24</td>
<td>170.66</td>
<td>0.00</td>
<td>1007410.80</td>
</tr>
<tr class="even">
<td>2025-04-09</td>
<td>1007410.80</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>198.85</td>
<td>390.49</td>
<td>234.34</td>
<td>105.80</td>
<td>150.97</td>
<td>162.32</td>
<td>114.33</td>
<td>301.01</td>
<td>355.39</td>
<td>191.10</td>
<td>0.00</td>
<td>1007410.80</td>
</tr>
<tr class="odd">
<td>2025-04-10</td>
<td>1007410.80</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>190.42</td>
<td>381.35</td>
<td>227.11</td>
<td>99.93</td>
<td>148.69</td>
<td>163.56</td>
<td>107.57</td>
<td>289.16</td>
<td>353.62</td>
<td>181.22</td>
<td>0.00</td>
<td>1007410.80</td>
</tr>
<tr class="even">
<td>2025-04-11</td>
<td>1007410.80</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>198.15</td>
<td>388.45</td>
<td>236.20</td>
<td>103.14</td>
<td>151.73</td>
<td>166.91</td>
<td>110.93</td>
<td>293.45</td>
<td>353.86</td>
<td>184.87</td>
<td>0.00</td>
<td>1007410.80</td>
</tr>
<tr class="odd">
<td>2025-04-14</td>
<td>1007410.80</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>202.52</td>
<td>387.81</td>
<td>234.72</td>
<td>103.39</td>
<td>154.36</td>
<td>169.13</td>
<td>110.71</td>
<td>298.12</td>
<td>357.20</td>
<td>182.12</td>
<td>0.00</td>
<td>1007410.80</td>
</tr>
<tr class="even">
<td>2025-04-15</td>
<td>1007410.80</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>202.14</td>
<td>385.73</td>
<td>233.13</td>
<td>103.10</td>
<td>153.62</td>
<td>168.47</td>
<td>112.20</td>
<td>293.43</td>
<td>354.11</td>
<td>179.59</td>
<td>0.00</td>
<td>1007410.80</td>
</tr>
<tr class="odd">
<td>2025-04-16</td>
<td>1007410.80</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>194.27</td>
<td>371.61</td>
<td>229.61</td>
<td>104.19</td>
<td>153.91</td>
<td>166.39</td>
<td>104.49</td>
<td>290.14</td>
<td>345.99</td>
<td>174.33</td>
<td>0.00</td>
<td>1007410.80</td>
</tr>
<tr class="even">
<td>2025-04-17</td>
<td>1007410.80</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>196.98</td>
<td>367.78</td>
<td>231.96</td>
<td>106.92</td>
<td>157.47</td>
<td>170.63</td>
<td>101.49</td>
<td>294.25</td>
<td>355.06</td>
<td>172.61</td>
<td>0.00</td>
<td>1007410.80</td>
</tr>
<tr class="odd">
<td>2025-04-21</td>
<td>1007410.80</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>193.16</td>
<td>359.12</td>
<td>228.99</td>
<td>105.35</td>
<td>156.92</td>
<td>165.75</td>
<td>96.91</td>
<td>284.74</td>
<td>346.90</td>
<td>167.32</td>
<td>0.00</td>
<td>1007410.80</td>
</tr>
<tr class="even">
<td>2025-04-22</td>
<td>1007410.80</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>199.74</td>
<td>366.82</td>
<td>235.59</td>
<td>108.30</td>
<td>157.75</td>
<td>167.88</td>
<td>98.89</td>
<td>291.17</td>
<td>354.43</td>
<td>173.18</td>
<td>0.00</td>
<td>1007410.80</td>
</tr>
<tr class="odd">
<td>2025-04-23</td>
<td>1007410.80</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>204.60</td>
<td>374.39</td>
<td>240.88</td>
<td>107.37</td>
<td>155.38</td>
<td>165.73</td>
<td>102.71</td>
<td>295.77</td>
<td>356.42</td>
<td>180.60</td>
<td>0.00</td>
<td>1007410.80</td>
</tr>
<tr class="even">
<td>2025-04-24</td>
<td>1007410.80</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>208.37</td>
<td>387.30</td>
<td>244.64</td>
<td>108.63</td>
<td>154.93</td>
<td>159.53</td>
<td>106.43</td>
<td>306.86</td>
<td>359.64</td>
<td>186.54</td>
<td>0.00</td>
<td>1007410.80</td>
</tr>
<tr class="odd">
<td>2025-04-25</td>
<td>1007410.80</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>209.28</td>
<td>391.85</td>
<td>243.55</td>
<td>108.57</td>
<td>154.58</td>
<td>161.02</td>
<td>111.01</td>
<td>306.45</td>
<td>357.58</td>
<td>188.99</td>
<td>0.00</td>
<td>1007410.80</td>
</tr>
<tr class="even">
<td>2025-04-28</td>
<td>1007410.80</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>210.14</td>
<td>391.16</td>
<td>243.22</td>
<td>108.63</td>
<td>155.35</td>
<td>161.85</td>
<td>108.73</td>
<td>307.06</td>
<td>356.92</td>
<td>187.70</td>
<td>0.00</td>
<td>1007410.80</td>
</tr>
<tr class="odd">
<td>2025-04-29</td>
<td>1007410.80</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>211.21</td>
<td>394.04</td>
<td>244.62</td>
<td>108.36</td>
<td>155.91</td>
<td>162.26</td>
<td>109.02</td>
<td>307.40</td>
<td>359.00</td>
<td>187.39</td>
<td>0.00</td>
<td>1007410.80</td>
</tr>
<tr class="even">
<td>2025-04-30</td>
<td>1007410.80</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>210.77</td>
<td>390.06</td>
<td>242.25</td>
<td>105.04</td>
<td>155.81</td>
<td>161.97</td>
<td>106.95</td>
<td>303.57</td>
<td>357.69</td>
<td>181.88</td>
<td>0.00</td>
<td>1007410.80</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<script>
document.addEventListener("DOMContentLoaded", function () {
  const input = document.getElementById("ledger-search");
  input.addEventListener("keyup", function () {
    const filter = input.value.toLowerCase();
    const rows = document.querySelectorAll("#ledger-table tbody tr");
    rows.forEach(row => {
      const dateCell = row.cells[0]?.textContent?.toLowerCase() || "";
      if (dateCell.includes(filter)) {
        row.style.display = "";
      } else {
        row.style.display = "none";
      }
    });
  });
});
</script>
<hr>
</section>
</section>
<section id="performance-analysis" class="level4">
<h4 class="anchored" data-anchor-id="performance-analysis"><strong>Performance Analysis</strong></h4>
<h5 class="anchored">
initial capital: 1M
</h5>
<p><strong>End-of-Day Market Value Comparison</strong> <iframe src="static/market_value_comparison.html" width="100%" height="568" frameborder="0"></iframe></p>
<p><strong>Drawndowns Comparison</strong> <iframe src="static/drawdowns_comparison.html" width="100%" height="568" frameborder="0"></iframe></p>
</section>
<section id="strategy-metrics-summary" class="level4">
<h4 class="anchored" data-anchor-id="strategy-metrics-summary"><strong>Strategy Metrics Summary</strong></h4>
<div id="7fbcf47c" class="cell" data-execution_count="12">
<div class="cell-output cell-output-display">
<table id="performance-table" class="dataframe table table-striped caption-top table-sm small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Metrics</th>
<th data-quarto-table-cell-role="th">Original</th>
<th data-quarto-table-cell-role="th">After Controlling Lever</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>alpha(benchmark: S&amp;P 500)</td>
<td>-0.13%</td>
<td>0.01%</td>
</tr>
<tr class="even">
<td>beta(benchmark: S&amp;P 500)</td>
<td>0.32</td>
<td>0.06</td>
</tr>
<tr class="odd">
<td>Cumulative Return</td>
<td>-16.48%</td>
<td>0.89%</td>
</tr>
<tr class="even">
<td>Geometric Mean Return</td>
<td>-31.06%</td>
<td>1.84%</td>
</tr>
<tr class="odd">
<td>Average Return per Trade</td>
<td>-0.27%</td>
<td>0.01%</td>
</tr>
<tr class="even">
<td>Annualized Volatility</td>
<td>27.28%</td>
<td>6.76%</td>
</tr>
<tr class="odd">
<td>Sharpe Ratio(rf=0.046)</td>
<td>-1.14</td>
<td>0.27</td>
</tr>
<tr class="even">
<td>Max Drawdown</td>
<td>26.63%</td>
<td>5.72%</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="performance-analysis-1" class="level4">
<h4 class="anchored" data-anchor-id="performance-analysis-1"><strong>Performance Analysis</strong></h4>
<ul>
<li><strong>Growth trajectory:</strong> Without leverage control, the portfolio ended below the starting capital ($1 M → $0.83M), reflecting a net loss. With leverage control, it modestly grew ($1 M → $1.01M), demonstrating sustainable gains.</li>
<li><strong>Cumulative &amp; geometric returns:</strong> Controlled leverage turned a deep drawdown into positive growth, and the market value of portfolio kept higher than at begining over the period, confirming mean reversion works when risk is contained.</li>
<li><strong>Per-trade efficiency:</strong> Average return per trade improved from <strong>–0.27%</strong> to <strong>+0.01%</strong>, indicating higher hit rate and profitability.</li>
<li><strong>Risk metrics:</strong> Volatility dropped from <strong>27.28%</strong> to <strong>6.76%</strong>, and max drawdown shrank from <strong>26.63%</strong> to <strong>5.72%</strong>, showcasing tighter drawdown control.</li>
<li><strong>Sharpe ratio shift:</strong> From <strong>–1.14</strong> (underperforming risk-free) to <strong>0.27</strong> (delivering positive risk-adjusted return).</li>
</ul>
<p>This shows that <strong>mean reversion signals</strong> can generate returns, but only disciplined risk management is necessary, such as controlling lever and limiting the weight of single asset. <strong>Leverage control</strong> transforms a volatile, loss‐making process into a stable, profitable strategy.</p>
</section>
</section>
<section id="limitations-and-future-enhancements" class="level3">
<h3 class="anchored" data-anchor-id="limitations-and-future-enhancements">Limitations and Future Enhancements</h3>
<p>Even with leverage control, the current implementation has several limitations:</p>
<ol type="1">
<li><strong>Simplistic Signal Framework</strong>:
<ul>
<li>Relies solely on fixed-threshold scores for EMA deviation, MACD, ADX, ATR, IV, and yield spread.</li>
<li>Does not adapt thresholds to changing market regimes (e.g., high-volatility vs.&nbsp;low-volatility periods).</li>
</ul></li>
<li><strong>Lack of Transaction Cost Modeling</strong>:
<ul>
<li>Omits commissions, slippage, and spreads, which can erode returns—especially for short-term or high-turnover strategies.</li>
</ul></li>
<li><strong>Ignoring Market Microstructure</strong>:
<ul>
<li>Hourly and daily data may not capture intraday liquidity constraints or order-book dynamics, leading to unrealistic execution assumptions.</li>
</ul></li>
<li><strong>No Regime Detection or Regime-Based Allocation</strong>:
<ul>
<li>Treats all periods equally; fails to switch off mean reversion signals during strong trending environments (e.g., bull/bear markets).</li>
</ul></li>
<li><strong>Uniform Indicator Weighting</strong>:
<ul>
<li>Assigns fixed weights to each indicator; does not account for their varying predictive power over time. A dynamic or machine-learning–based weighting scheme could improve signal quality.</li>
</ul></li>
<li><strong>Single Timeframe Analysis</strong>:
<ul>
<li>Uses daily and hourly frequencies but ignores higher-frequency signals or multi-timeframe confirmation that can reduce false signals.</li>
</ul></li>
<li><strong>Tail Risk and Black Swan Events</strong>:
<ul>
<li>Lacks a stress-test mechanism for extreme market moves or systemic shocks. Consider adding volatility overlays or drawdown limits.</li>
</ul></li>
</ol>
<section id="future-enhancements" class="level4">
<h4 class="anchored" data-anchor-id="future-enhancements"><strong>Future Enhancements</strong>:</h4>
<ul>
<li><p>Implement regime-switching to adapt thresholds and weights.</p></li>
<li><p>Incorporate transaction cost estimates into portfolio optimization.</p></li>
<li><p>Explore multi-timeframe signals and alternative data (e.g., sentiment, order flow).</p></li>
<li><p>Use adaptive indicator weighting via machine learning or Bayesian updating.</p></li>
<li><p>Add tail-risk protection, such as option hedges or dynamic stop adjustments.</p></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>